### ISSUE TITLE
Juniper vSRX appliance is extremely slow in GNS3-VM

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-registry#102]
Tested with junos-vsrx-12.1X47-D20.7-domestic.ova

While the appliance works fine in bare-metal linux, it's doesn't work well in the GNS3 VM. The boot phase is fine, but interacting afterwards with the cli is extremely slow. After adding `-machine type=pc-1.0` to the qemu options, it greatly improves. It's still slower and needs more CPU as on a bare-metal linux or as a VirtualBox or VMware VM, but it's running reasonably well.

So I suggest to change the qemu option to `-smp 2 -machine type=pc-1.0`

I haven't tested the v15 vSRX images, these are monsters.

**Comment by agould123** [comment]
I'm booting (2) vSRX instances of 15.1X49-D140.2 in EVE-NG.  I'm running EVE-NG on my Dell Precision 5510 laptop (intel xeon quad core, 32 gig ram).  eve-ng ubuntu vm takes a few minutes to boot up....

...after that, the vSRX Junos 15.1.....D140 instances take about 8 minutes to boot up.... after they boot up and settle down, they run nicely.  Granted, I've only tested ping between them over a link using fxp0, but seems good so far.
