### ISSUE TITLE
Extending qemu schema for multiple vCPUs

### ISSUE THREAD

**Issue by adosztal** [GNS3/gns3-registry#112]
I'm creating a template for Cisco vNAM. This appliance requires 2 vCPUs (CLI option: -smp cpus=2) but it doesn't exist in the schema file. Would it be possible to add and parse this under qemu in appliance.json?
```
"cpus": {
  "type": "integer",
  "title": "Number of virtual CPUs allocated to the appliance"   
},
```

**Comment by noplay** [comment]
For the moment it's supported via the options field:
https://github.com/GNS3/gns3-registry/blob/master/appliances/cisco-iosxrv9k.gns3a#L24

I'm not against this field but this will make the appliance not compatible with current release. We can later convert this field when we will have a proper support.

**Comment by adosztal** [comment]
Options field is totally fine for me, I just didn't know about it. :) You can ignore the question.

**Comment by adosztal** [comment]
Btw the vNAM didn't go well, got stuck during DB initialization for some reason.

**Comment by noplay** [comment]
You can check the parameter use by unetlab:
https://github.com/dainok/unetlab/blob/04dc5cd1a125101e6031e8f0c322d216de2c74d9/html/templates/vnam.php
