### ISSUE TITLE
Juniper VMX support seem not working

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-registry#116]
https://gns3.com/qa/juniper-vmx-on-gns3-vm-not-getti

That sound complicate to make it work

**Comment by adosztal** [comment]
Newer versions (15.x/16.x) seem to support KVM; I'm checking it today/tomorrow.

**Comment by adosztal** [comment]
Nah, 16.1R1 works the same way as described in the post. :(

**Comment by noplay** [comment]
:(

**Comment by grossmj** [comment]
Looks like this works: https://docs.gns3.com/144QvvLxBT69_fv-pPHf4etc5xjdItiA_a8s8gVmSTDk/index.html
