### ISSUE TITLE
Windows appliance broken

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-registry#121]
The Windows XP VM is no longer offered and should therefore be removed.

The Windows 7 VM doesn't work:
- 512 MB is far below the minimum that Microsoft recommends (1 GB)
- The pcnet adapter type is not recognized (e1000 is)
- The es1370 sound is not recommended, see http://www.linux-kvm.org/page/Sound

I tried to change the settings, so Windows 7 will run, but I failed. The VM basically runs, but not so well, that it can be recommended.

I suggest to delete this appliance.

**Comment by noplay** [comment]
Agree, @grossmj  ?

**Comment by grossmj** [comment]
Yes

**Comment by noplay** [comment]
Removed from the marketplace
