### ISSUE TITLE
Interface sequence number can only start from 0 or 1

### ISSUE THREAD

**Issue by adosztal** [GNS3/gns3-registry#141]
Two common examples for 4 interfaces:
- eth{0} --> eth0 to eth3
- port{port1} --> port1 to port4

I'm working on a template for Brocade vRouter, which has a weird interface naming: dp0s3 to dp0s6 with 4 interfaces. The problem is I can only name the first interface dp0s0 or dp0s1 (dp0s{0} or dp0s{port1}).

For now I think I'll just name them ethx but would it possible to set the starting sequence number in a later release (maybe 2.0)?

**Comment by adosztal** [comment]
@noplay, @grossmj?

**Comment by noplay** [comment]
You need something like  dp0s{3} ?

**Comment by adosztal** [comment]
Kind of, but {1} is already used for segments, which could result in a conflict for other appliances later on. Imagine someone trying to create a template where the first interface is dp0s1; he enters dp0s{1} and gets an error.
I know there's a workaround because dp0s1 can be described with dp0s{port1} but this behavior is not consistent.

Maybe dp0s{0,3} where 0 identifies the port and the 3 is the starting sequence number?

**Comment by noplay** [comment]
What do you think Jeremy?

**Comment by adosztal** [comment]
Fix for the suggested format: starting sequence number might be optional, like **dp0s{0[,3]}**.

**Comment by noplay** [comment]
@grossmj ?

**Comment by noplay** [comment]
This issue was moved to GNS3/gns3-server#654

**Comment by noplay** [comment]
Issue moved to GNS3 server in order to not forget to fix that for 2.0

@adosztal I recommend you to watch the new issue in order to get comments.
