### ISSUE TITLE
Update TinyCore version?

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-registry#143]
We are currently using v6.4, TinyCore is currently approaching v7.2. Main changes are an updated kernel.

Do we want to put some effort to update our tinycore based VMs?

We won't gain much, the difference between 6.x and 7.x is mainly a new kernel and some improvements in the internal tools. On the other side, if we don't update, we have to support VMs with an outdated base VM.

I'm asking, because the next ostinato version 0.8 is on it's way and I want to know, what tinycore base to choose.

**Comment by grossmj** [comment]
I am for updating Tinycore to the latest version but to be really useful some tools should be included by default, like iperf tcpdump etc.

For info here are things that were included in old custom images: http://forum.gns3.net/topic3928.html

**Comment by noplay** [comment]
I think with docker we have a solution for most use case where tinycore was usefull.

With ostinato update you can try to change the iso and see if install work fine, it should easy if they changed nothing else.

**Comment by ehlers** [comment]
Yes, I think that docker images will be a good replacement for most tinycore appliances. But as the docker integrations is quite new I will release ostinato 0.8 as a tinycore VM. The next ostinato version will most likely be based on docker.

I'm still undecided which tinycore version to use. Version 7.x have no real improvements besides a newer kernel. I will decide during the integration.

**Comment by noplay** [comment]
Agree
