### ISSUE TITLE
Mininet VM

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-registry#16]
http://mininet.org/vm-setup-notes/

Depending of .ova support #15

**Comment by noplay** [comment]
Perhaps possible also using docker

**Comment by adosztal** [comment]
Mininet now provides an OVF + VMDK archive. I'll add it.

**Comment by adosztal** [comment]
Oops, I forgot about it; anyway the Mininet Team has added it: https://github.com/GNS3/gns3-registry/blob/master/appliances/mininet.gns3a
This issue can be closed.
