### ISSUE TITLE
Add a field about the type of access to an appliance

### ISSUE THREAD

**Issue by julien-duponchelle** [GNS3/gns3-registry#165]
A field with the information:
- this appliance is free to download
- this appliance require a free user account
- this appliance require a trial key
- this appliance require a paid support

I don't know how exactly we should call this field but in order to improve the marketplace on gns3.com (
https://gns3.com/discussions/request-for-organizing-the-appli) or the appliance wizard.

**Comment by adosztal** [comment]
I'd avoid "license" as it might lead to confusions. How about "availability" or "image-availability"?

**Comment by noplay** [comment]
Availability sound like a good idea.

**Comment by adosztal** [comment]
Something like this?
```
    "availability": {
      "enum": ["free", "with-registration", "free-to-try", "service-contract"],
      "title": "About image availability: can be downloaded directly; download requires a free registration; paid but a trial version (time or feature limited) is available; not available publicly"
    },
```

**Comment by noplay** [comment]
Seem good. What do you think @grossmj ?

**Comment by adosztal** [comment]
After agreeing on the format, I can make a branch for the updated appliance.json and .gns3a files.

**Comment by adosztal** [comment]
Here's the suggested solution: https://github.com/adosztal/gns3-registry/commit/2d8c1d4f47ff4e2e384a04761947f0f1340456e3
Keep it / change it / drop it?

**Comment by noplay** [comment]
I just revert the merge because it's break current GNS3 release:
![error1](https://cloud.githubusercontent.com/assets/345437/19772926/fff82370-9c67-11e6-8d42-d352a9e30cb3.png)

I need to check how we can relax that

**Comment by noplay** [comment]
For me it's sound good and if we want to change we can script the
modification.

**Comment by grossmj** [comment]
This is good, let's use availability.

**Comment by adosztal** [comment]
@noplay, what if I
- revert my master branch too;
- create a PR for my "availability" branch;
- keep the version updates synchronized between the two branches?

This way you can merge the "availability" branch at a time convenient for you, after fixing the current release.

**Comment by noplay** [comment]
Sound good to me

**Comment by adosztal** [comment]
Done.
Btw, I scripted the modification with this [small one](https://gist.github.com/adosztal/ab57ce222e0b9a5b2b5e4b009927fa2e). :)

**Comment by noplay** [comment]
Need to wait 1.5.3 before changing appliances files

**Comment by adosztal** [comment]
That branch conflict appears every time I start committing changes to both. I'll keep the registry v4 files on a local drive; please drop a message here when I can commit them to my master branch, then I'll make the PR.

**Comment by noplay** [comment]
I move this to 2.1 because for the moment we need to wait everyone upgrade to compatible client before changing that

**Comment by adosztal** [comment]
No problem, I'll keep the files updated.

**Comment by noplay** [comment]
Thanks a lot for the help

**Comment by noplay** [comment]
Ok 1.5.3 is shipped we can change the registry now

**Comment by noplay** [comment]
1.5 still create trouble with that... Until user migrate to 2.0 we can't modify the appliances ....

**Comment by grossmj** [comment]
We will update the appliance files once we release version GNS3 version 2.2

**Comment by adosztal** [comment]
Ping me before the release and I'll update every appliance.

**Comment by grossmj** [comment]
This has been implement a while ago ;)
