### ISSUE TITLE
MicroCore Linux version are quite old

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-registry#18]
Why this old versions?

I can understand, when people are using MicroCore V4.x (latest is 4.7.7), as more extensions are available than for 6.x. But 3.4.1 and 4.0.2 are really old.

Brezular has some really nice stuff at http://brezular.com/2013/09/17/linux-core-appliances-download/ . I suggest to use the 6.3 version (must be converted from vmdk to qcow2 and then uploaded to sourceforge) and the 4.7.7 version.

Furthermore his Quagga, Openvswitch and Bird version looks interesting as well.

**Comment by noplay** [comment]
We plan to update them.

A nice to have is a packer script allowing to rebuild the appliance.

**Comment by ehlers** [comment]
If it helps I could create an updated tinycore appliance. I would just use the images from Brezlar, verify RAM usage and description.

**Comment by noplay** [comment]
I will check during the week if it's hard to create a packer script.

It could be nice if anyone can take the packer script, add a package without the need to do all the configuration by hand.

**Comment by ehlers** [comment]
I just played a little bit with packer and generated a first test version, see https://github.com/ehlers/gns3-registry/commit/5e9f0fcc1de62cd14ef7b35647104227ade896ad

**Comment by noplay** [comment]
Awesome !

**Comment by ehlers** [comment]
Updated my Tiny Core packer to support V4.x, tested only with 4.7.7. Also some cleanup done.

Next step is to create a packer for NETem.

**Comment by noplay** [comment]
Do you want to make a PR for tiny core? I can merge it, build and push an
image on sourceforge.

**Comment by ehlers** [comment]
Well, I could. But for me there are some open questions:
- What packages should be included? Currently I added openssh, ipv6, iptables, iproute2, tcpdump and iperf3. Is something important missing?
- How to name it? Since V4.2 (since 2012) the Tiny Core guys no longer use the term MicroCore, therefore I used TinyCore. But a GUI version would also use that name.

**Comment by noplay** [comment]
We can name it core because it's the name of the ISO.

For package I suggest a naked version with nothing and a network admin toolbox where we put all the require package.

I can take care of polishing stuff.

**Comment by ehlers** [comment]
Just created the PR? I think it's better, if I leave that polishing to you. I'm not good in that,

**Comment by noplay** [comment]
I have opened issues for stuff like openvswitch
