### ISSUE TITLE
Juniper vSRX appliance doesn't boot with newer qemu

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-registry#197]
The option `-machine type=pc-1.0` introduced in issue https://github.com/GNS3/gns3-registry/issues/102 leads to a crash in the boot phase on qemu version 2.6 and newer. As the GNS3 VM currently uses qemu v2.5, it is not affected.

Nevertheless to support the newer qemu versions I suggest to remove the `-machine type=pc-1.0` option from the appliance.

The performance issue, that should be solved by this option seems to be present only on debian. For some more informations see https://www.gns3.com/discussions/running-vsrx-in-qemu

**Comment by noplay** [comment]
I pushed your changes
