### ISSUE TITLE
How to ship appliances with GNS3?

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-registry#203]
With https://github.com/GNS3/gns3-gui/issues/1045 we want to have the .gns3a available on the user machine. 

Their is multiple way to do it
# Include in the GNS3 server

Include the appliances directly in the GNS3 server repository.

## Pro
Easy

## Con
* Not easy to update
* Require to duplicate the gns3a
* You can not update the appliances when a .exe is shipped

# Create a GNS3 appliances package

Make a package with the appliances and upload it to PyPi and the launchpad ppa.

## Pro
* Could be automated to upload a new version at each commit on the master branch of gns3-registry
* Build process and installation could easily use the last version

## Con 
* You can not update the appliances when a .exe is shipped

# Download them from the net
## Pro
* Easy to update from the application

## Con
* You need an internet connection

**Comment by grossmj** [comment]
I think we should ship the most recent version of .gns3a with the GNS3 server and have an option to update from Internet or download the package.

I don't understand why you say we cannot update the appliances when we ship a .exe

**Comment by noplay** [comment]
We can't patch the files they could be in a location where we can't write. If It's a .deb for example we can't write in /usr/lib.

We can have an overlay location where we store the last appliances. For example ~/GNS3/appliances

It's easy to upgrade in this location. But how I know an appliance shipped with GNS3 is more recent than an appliance already on disk?
