### ISSUE TITLE
Application icons not loaded

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-registry#219]
If a user downloads an appliance, the user doesn't know that it offers a custom icon (e.g. the ostinato-3d-icon.svg). But unless he downloads and installs it manually the icon is not used.

A way for automatically downloading (and showing) the icon should be added.

**Comment by noplay** [comment]
The icon should already be downloaded from the registry:
https://github.com/GNS3/gns3-gui/blob/master/gns3/registry/config.py#L295

 It's not working for you ?

**Comment by ehlers** [comment]
I have to admit, that I haven't checked that for a long time, but I saw in David Bombal's videos, e.g. https://www.youtube.com/watch?v=SmFWlIhOEQY , that the ostinato symbol is not shown.

Just tested with plain GNS3 v1.5.4 and it works both for vRIN and for ostinato. I will mail David, if he can give us more details.

**Comment by noplay** [comment]
Perhaps blocked by a proxy or something like this

Le mer. 19 avr. 2017 à 09:46, Bernhard Ehlers <notifications@github.com> a
écrit :

**Comment by ehlers** [comment]
David's answer:
> To answer your question - on both the 0.8 and the new version, when I download the appliance from > the GNS3 marketplace and run it, the logo displayed is per the videos. I didn't change the logo.
> 
> I have been using version 2.0 of GNS3 in the videos - not sure that make any difference?

Just did a fresh install of GNS3 2.0.0rc3 for OS X and GNS3VM. Then I imported the ostinato appliance. No issue, the VM is shown with the ostinato logo.

No idea, how to proceed. Close it?

**Comment by noplay** [comment]
Perhaps internet was not accessible during the import. We fallback do the
default icon in this case.
