### ISSUE TITLE
Cisco FTDv and FMC  appliance

### ISSUE THREAD

**Issue by jhonnyx82** [GNS3/gns3-registry#224]
It may be good to have appliances for FTDv and FMC : 

here the download images:

https://software.cisco.com/download/release.html?mdfid=286306503&flowid=79503&softwareid=286306337&release=6.2.0.2&relind=AVAILABLE&rellifecycle=&reltype=latest

**Comment by noplay** [comment]
I don't have access to the download file. It seem image are provided as a
.sh that you need to execute on the machine. Not sure if their is way to
import in GNS3. Did you manage to import it?

**Comment by jhonnyx82** [comment]
There are also qcow images, version 6.1.0

Also there is a thread in ghe community page where an user already
installed it

**Comment by adosztal** [comment]
I checked but I don't have access to these images.

**Comment by jhonnyx82** [comment]
I managed to install these appliances.

I will create a templeate as soon as I can

**Comment by cioby23** [comment]
I think this can be closed as FMCv and FTDv appliances exists in the Marketplace.
https://gns3.com/marketplace/appliance/cisco-ftdv
https://gns3.com/marketplace/appliance/cisco-fmcv

**Comment by grossmj** [comment]
Correct :+1:
