### ISSUE TITLE
brocade-vadx and cisco-nxosv9k: change registry_version to 4

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-registry#234]
Both appliances are not valid version 3 appliances, but are fine version 4 apps.

These are the validation errors against the version 3 schema:

brocade-vadx.gns3a
['qemu']: Additional properties are not allowed ('cpus' was unexpected)

cisco-nxosv9k.gns3a
Additional properties are not allowed ('availability' was unexpected)
['qemu']: Additional properties are not allowed ('cpus' was unexpected)
['qemu']['hda_disk_interface']: 'sata' is not one of ['ide', 'scsi', 'sd', 'mtd', 'floppy', 'pflash', , 'virtio']
['versions']['images']: Additional properties are not allowed ('bios_image' was unexpected)

**Comment by ehlers** [comment]
An additional idea for check.py:
What about checking against the schema version, that is given in the .gns3a?

That would require, that not only the current schema is stored in the schemas directory, but also the previous versions.

**Comment by adosztal** [comment]
What about converting vADX back to the old format and add the "cpus" when the majority will use 2.x?
As for NXOSv9k, the UEFI BIOS makes v4 unavoidable.

**Comment by ehlers** [comment]
I support that. A possible guideline could be: Use version 3 if it's possible without giving up some features. Otherwise use version 4.

**Comment by adosztal** [comment]
Commit https://github.com/GNS3/gns3-registry/pull/232/commits/87fde3c7b41b7576ac2123b811681b8848adddca solves vADX.

**Comment by ehlers** [comment]
Commit c36523bcf498f2d429dffeadeabc7966fd9f9b0d solves cisco-nxosv9k.
