### ISSUE TITLE
Microcore openvswitch

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-registry#24]

**Comment by noplay** [comment]
It's broken on Openvswitch side:
http://forum.tinycorelinux.net/index.php/topic,18956.0.html

**Comment by ehlers** [comment]
Create a dummy extension openssl-1.0.0, that depends on openssl

From my mind, untested:
```
tce-load -wi squashfs-tools
mkdir /tmp/empty
mksquashfs /tmp/empty openssl-1.0.0.tcz
md5sum openssl-1.0.0.tcz > openssl-1.0.0.tcz.md5.dep
echo 'openssl.tcz' > openssl-1.0.0.tcz.dep
cp -p openssl-1.0.0.tcz* /mnt/sda1/tce/optional/
tce-load -i openssl-1.0.0.tcz
```

**Comment by noplay** [comment]
Package has been fixed by TinyCore

**Comment by noplay** [comment]
Now it's build, we need to configure it.

**Comment by ehlers** [comment]
Maybe Brezular can help.

**Comment by noplay** [comment]
A roadblock syslinux is not available for x64 via tinycore package. We need to switch to grub2 and compile syslinux.

I tried to install grub2 but failed :(

I tried also to use the 32 bit version of syslinux, but core64 doesn't support 32 bit binaries.

**Comment by ehlers** [comment]
Yes, that's the annoying part of TinyCore. Extensions are missing or buggy. You have to be prepared to do a lot yourself.

Normal strategies are to use the 64bit binaries of 5.x or 4.x, but for syslinux this fails as well. So either compile it yourself, or enhance Core64 to support 32bit binaries.

I once manually installed the 32bit binary stuff (I wanted a GNS3 VM with tinycore and needed the 32bit stuff fur IOUs). As you don't need a full lib32 extension, you can strip this down. But maybe it's easier to recompile syslinux.

```
# Make lib32 extension
tce-load -wi squashfs-tools
sudo -s
mkdir /tmp/lib32
cd /tmp/lib32
wget http://tinycorelinux.net/6.x/x86/release/Core-current.iso
mount -o loop Core-current.iso /mnt/fd0
mkdir lib32
cd lib32
zcat /mnt/fd0/boot/core.gz | cpio -id "lib/l*" "usr/lib/l*"
mkdir -p usr/local/lib
cd ..
umount /mnt/fd0
rm Core-current.iso
mkdir lib
ln -s /lib32/lib/`readlink lib32/lib/ld-linux.so.2` lib/ld-linux.so.2
mkdir -p usr/local/tce.installed
cat > usr/local/tce.installed/lib32 << 'EOF'
#!/bin/sh
echo -e "/lib32/lib\n/lib32/usr/lib\n/lib32/usr/local/lib" >> /etc/ld.so.conf
ldconfig
sed 's/ld-linux.*\*/ld-linux.so\*/' /usr/bin/ldd > /usr/bin/ldd32
chmod +x /usr/bin/ldd32
sed 's/ld-linux/ld-linux-x86-64/' /usr/bin/ldd32 > /usr/bin/ldd
chmod +x /usr/bin/ldd
EOF
chmod +x usr/local/tce.installed/lib32
chgrp -R staff usr/local/tce.installed
chmod 775 usr/local/tce.installed
exit
mksquashfs /tmp/lib32 lib32.tcz
mv lib32.tcz* /mnt/sda1/tce/optional/
echo lib32.tcz >> /mnt/sda1/tce/onboot.lst 
tce-load -i /mnt/sda1/tce/optional/lib32

#load syslinux
wget http://repo.tinycorelinux.net/6.x/x86/tcz/syslinux.tcz
tce-load -i syslinux.tcz
```

**Comment by noplay** [comment]
Thanks for the workaround. I will clean it and use it.

**Comment by grossmj** [comment]
:+1:

**Comment by noplay** [comment]
I got a working switch. I just need to do the gns3a file.

**Comment by ehlers** [comment]
You created the lib32 extension during hd-install-64bits.sh. As you need the 32 bit libraries only for syslinux, that's not really necessary. For a one time usage of the 32 bit libraries, quite some commands can be left out.

Shall I create a stripped down version of hd-install-64bits.sh without the creation of the lib32 extension? Or do you prefer having a lib32 extension available for other 32bit programs?

**Comment by noplay** [comment]
You can create a stripped version. If we can remove some stuff it's better.
