### ISSUE TITLE
[proposal]  Add ab (Apache benchmark) to webterm container.

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-registry#248]
Beside manual browsing using firefox, we could add ab (Apache benchmark), a very useful and easy tool to  generate http traffic.

`RUN apt-get update && apt-get -y install apache2-utils`

**Comment by noplay** [comment]
Hi, you can make a PR with that. I think we can merge it without problem

**Comment by AJNOURI** [comment]
The updated webterm image works fine:

![selection_0147](https://user-images.githubusercontent.com/1716020/28422506-83975792-6d68-11e7-807e-7c602ad5f815.png)

Created webterm directory with Dockerfile (don't exist) and updated the corresponding appliance file.
https://github.com/GNS3/gns3-registry/pull/249
