### ISSUE TITLE
Windows XP appliance?

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-registry#256]
The XP appliance was pulled from the gns3-registry because Microsoft stopped offering the VM. But https://github.com/magnetikonline/linuxmicrosoftievirtualmachines discovered, that these images are still available on the microsoft servers, only the links to the download location were removed from the microsoft web site.

So technically it should be possible to get it back to the gns3-registry. The VM is relative small, works quite well with qemu and is a nice testbed for small windows utilities. But XP is severely outdated and a security problem.

So, do you want to get XP back? Or should it be keep it in it's grave?

**Comment by grossmj** [comment]
I think there is no harm having it back.

**Comment by ehlers** [comment]
Abandoned it, Windows run just awful in QEMU.
