### ISSUE TITLE
Docker build not in proper sequence

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-registry#261]
Docker Hub builds the images in an undefined order. Initially I thought it builds in the order, the images are added to Docker Hub, but that's not always true.

This is an issue for images, where you have a base image and others depending on that, e.g. ipterm-base is a base image, ipterm and webterm depend on it. The base image should be build first, but that's currently not the case:

| Image  | Creation Date |
| ------------- | ------------- |
| gns3/ipterm       | 2017-08-18T13:52:36.903788413Z |
| gns3/webterm | 2017-08-18T13:55:28.028588937Z |
| gns3/ipterm-base | 2017-08-18T13:59:11.463455837Z |

I was facing the same issue in my 'ehlers' repository. But I think, I've got a good solution.

The build settings of all images, that are not dependent of another base image and all base images  stay the same, as they currently are. The rest (currently only ipterm and webterm) gets the following settings (here from my 'ehlers' repository):
![ip-term](https://user-images.githubusercontent.com/896406/29493505-00952214-8598-11e7-87b0-98585a3825c4.png)

The option to start the build on pushes gets unticked. That way a commit on GitHub doesn't start the automatic build. Furthermore the base image is added as a repository link. That way any change to the base image triggers a build. So the dependent images are build after the base image.

This works great on my repository, maybe that idea can be implemented here as well.

**Comment by noplay** [comment]
Thanks I apply your suggestion
