### ISSUE TITLE
Connection is shown in transparent area within Microsoft logo 

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-registry#265]
The microsoft logo is transparent between the four squares. When using that in GNS3, it doesn't look nice, when the connections happen to go through this transparent space.
![win_svg_old](https://user-images.githubusercontent.com/896406/29767008-1c9f0a52-8be1-11e7-8129-d45b254227c8.png)

By adding a bigger white area below the four squares, the connections start at the border of the logo.
![win_svg_new](https://user-images.githubusercontent.com/896406/29767015-1fda3868-8be1-11e7-9d57-b2a51773876c.png)

These are my changes to microsoft.svg:

```
--- microsoft.svg.orig	2017-08-28 10:35:13.000000000 +0200
+++ microsoft.svg	2017-08-28 11:01:22.000000000 +0200
@@ -48,6 +48,13 @@
      inkscape:window-maximized="1"
      inkscape:current-layer="svg2" />
   <rect
+     height="64.5785798"
+     width="64.5785805"
+     x="2.7154145"
+     y="2.8091612"
+     id="rect0"
+     style="fill:#ffffff" />
+  <rect
      height="30.933941"
      width="30.933941"
      x="2.7154145"
```

**Comment by grossmj** [comment]
Thanks :+1:

**Comment by adosztal** [comment]
Thanks Bernhard, I overlooked this.
