### ISSUE TITLE
installing gns3 appliances

### ISSUE THREAD

**Issue by suniljoe11** [GNS3/gns3-registry#267]
how to install the appliances in gns3 for free?

**Comment by noplay** [comment]
You will get informations here:
http://docs.gns3.com/1MAdxz0BSEAfGM7tA-w-o3TMmf8XOx7nBf0z6d9nRz_c/index.html

Le ven. 1 sept. 2017 à 08:55, suniljoe11 <notifications@github.com> a
écrit :
