### ISSUE TITLE
vSRX Network Settings incorrect

### ISSUE THREAD

**Issue by binarycow** [GNS3/gns3-registry#314]
On the vSRX (for at least version vSRX15.1X49-D90-1), the network adapter type should be vmxnet3.  In addition, the first port name should be "fxp0"

**Comment by grossmj** [comment]
@adosztal are you okay we change these settings? I cannot test on my side.

**Comment by adosztal** [comment]
I can test it around Thu/Fri but I think you can commit it; if it's not working, it won't be worse.

**Comment by binarycow** [comment]
For what its worth, I've tested it on my machine, and these are well known issues.

See [here](https://forums.juniper.net/t5/vSRX/My-virtual-SRX-doesn-t-see-any-phisical-interface/td-p/300967) for the vmxnet3 issue as well as mentions of the 'first port' issue.

[This link](https://docs.gns3.com/144QvvLxBT69_fv-pPHf4etc5xjdItiA_a8s8gVmSTDk/index.html) is about the vMX and vQFX (which also have port naming issues) that discusses the port naming in more detail.  Interestingly enough, for that guide, they are using the 'e1000' port type, but that may be because they're not using the GNS3 VM?

**Comment by adosztal** [comment]
Fixed, this issue can be closed.
