### ISSUE TITLE
Multiple invalid appliances

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-registry#32]
Jeremy's last cleanup created some invalid appliances:

cisco-asa.gns3a
cisco-asav.gns3a
cisco-iosv.gns3a
cisco-iosvl2.gns3a
cisco-nxosv.gns3a
vyos.gns3a

@grossmj should really use check.py

**Comment by noplay** [comment]
Fixed :)

**Comment by grossmj** [comment]
Eh? I will make sure I use check.py in the future ;)
