### ISSUE TITLE
Typo: .124-24. --> .124-25.

### ISSUE THREAD

**Issue by artashus** [GNS3/gns3-registry#321]
Hi,

https://github.com/GNS3/gns3-registry/blob/764adb2613b968dc475018528def8eabcd36dfaa/appliances/cisco-7200.gns3a#L24

Given above as well as L35, should not `.*124-24.T5.image` be `.*124-25.T5.image` ?

Best,
Artashes

**Comment by grossmj** [comment]
Fixed in https://github.com/GNS3/gns3-registry/commit/e0641da9d5142dc5161a74f14ca6a684aad9e0be

The image c7200-adventerprisek9-mz.124-24.T5 is listed in https://docs.gns3.com/1-kBrTplBltp9P3P-AigoMzlDO-ISyL1h3bYpOl5Q8mQ/index.html#h.1i702f9cy8ho

Thanks for spotting this :+1:
