### ISSUE TITLE
Cloudrouter

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-registry#33]
It seem easy to support that:
https://github.com/cloudrouter/cloudrouter

They provide a KVM image.

**Comment by noplay** [comment]
It's interesting because they provide a raw image of 6GB (2,4GB if you convert it to qcow2). Upload it to the vm has failed on my computer due to the fact I don't have enough disk space. 

The problem is I have three copy of the images:
* one in my download directory
* one in my images directory
* one on the vm

With large image we can quickly explode the disk usage

**Comment by noplay** [comment]
I pushed a sample of config file for cloudrouter:
837a86bdbceaf77dadf762317b04fe31d6f9e669

It boot but auth is not working

**Comment by adosztal** [comment]
```
-bash-4.2$ sudo ip addr add 192.168.1.2/24 dev eth0
[sudo] password for cloudrouter: 
-bash-4.2$ ping 192.168.1.1
PING 192.168.1.1 (192.168.1.1) 56(84) bytes of data.
64 bytes from 192.168.1.1: icmp_seq=1 ttl=255 time=0.781 ms
64 bytes from 192.168.1.1: icmp_seq=2 ttl=255 time=0.262 ms

```
I made a custom cloudrouter-init.iso, and I can login with that. ;) I'll share it with you soon.
