### ISSUE TITLE
CSR 16.x default network adapter change

### ISSUE THREAD

**Issue by dmfigol** [GNS3/gns3-registry#337]
So apparently, dot1q on CSR1000v with **virtio** vnic is not working, but it is working fine with **vmxnet3** driver on any 16.x release. I haven't tested 15.x releases
I have been using vmxnet3 for some time and haven't found any issues.
Is it ok if we change default vnic type to vmxnet3?
Thanks!

**Comment by grossmj** [comment]
I cannot test on my side. @adosztal what do you think?

**Comment by adosztal** [comment]
I found a [Cisco document](https://www.cisco.com/c/en/us/td/docs/routers/csr1000/software/configuration/b_CSR1000v_Configuration_Guide/b_CSR1000v_Configuration_Guide_chapter_00.html) that states vmxnet3 is supported on the 3.1x releases too.

**Comment by dmfigol** [comment]
@adosztal Officially vmxnet3 is supported only for ESXi hypervisor.
For KVM - only virtio

**Comment by adosztal** [comment]
Then why did you ask to change it if it's not supported (for 16.x as well)?
