### ISSUE TITLE
Update FRRouting appliance

### ISSUE THREAD

**Issue by Najihel** [GNS3/gns3-registry#346]
Hello,

Could you please update the FRRouting appliance to FRR 5 (if possible with SNMP AgentX included) ?

https://github.com/FRRouting/frr/releases/latest

Thanks !

**Comment by adosztal** [comment]
Sorry, I missed this one. I updated the appliance with FRR 6.0.

**Comment by grossmj** [comment]
Fixed by https://github.com/GNS3/gns3-registry/pull/386
