### ISSUE TITLE
GNS3 crashes after installing a custom appliance file

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-registry#361]
GNS3 crashes after installing a custom appliance file and click on any of the device category:

Looks like something wrong with "category" in the below appliance file:

```
{
    "name": "Tacacsgui",
    "category": "firewall",
    "description": "TacacsGUI Free Access Control Server for Your Network Devices. GUI for powerful daemon. The project of Alexey Mochalin, based on tacacs daemon by Marc Huber",
    "vendor_name": "tacacsgui",
    "vendor_url": "https://tacacsgui.com/",
    "documentation_url": "https://tacacsgui.com/documentation/",
    "product_name": "tacacsgui",
    "product_url": "https://drive.google.com/open?id=1U8tbj14NqEyCmarayhZm54qTyjgsJm4B",
    "registry_version": 3,
    "status": "stable",
    "maintainer": "GNS3 Team",
    "maintainer_email": "developers@gns3.net",
    "usage": "Credentials: SSH ---> username: root ---> password: 1234 MySQL DB: ---> username: root --> password: tacacs Web interface: ---> username: tacgui ---> password: abc123",
    "port_name_format": "Port{port1}",
    "qemu": {
        "adapter_type": "e1000",
        "adapters": 1,
        "ram": 1024,
        "hda_disk_interface": "ide",
        "arch": "x86_64",
        "console_type": "telnet",
        "boot_priority": "c",
        "kvm": "allow"
    },
    "images": [
        {
            "filename": "tac_plus.qcow2",
            "version": "201710201114",
            "md5sum": "6b5e66590051124dae586b8640b2eb11",
            "filesize": 160301056,
            "download_url": "https://drive.google.com/open?id=1U8tbj14NqEyCmarayhZm54qTyjgsJm4B"
        }
    ],
    "versions": [
        {
            "name": "201710201114",
            "images": {
                "hda_disk_image": "tac_plus.qcow2"
            }
        }
    ]
}
```

And here is the error:

> 2018-08-20 21:44:16 WARNING appliance_wizard.py:94 '/home/ajn/GNS3/appliances/tacacsgui.gns3a' and '/home/ajn/GNS3/appliances/tacacsgui.gns3a' are the same file
> ****** Exception detected, traceback information saved in /home/ajn/.config/GNS3/exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.9-py3.6.egg/gns3/main_window.py", line 1000, in _browseEndDevicesActionSlot
>     self._showNodesDockWidget("End devices", Node.end_devices)
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.9-py3.6.egg/gns3/main_window.py", line 972, in _showNodesDockWidget
>     self.uiNodesDockWidget.populateNodesView(category)
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.9-py3.6.egg/gns3/nodes_dock_widget.py", line 63, in populateNodesView
>     self.parent().uiNodesView.populateNodesView(category, text)
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.9-py3.6.egg/gns3/nodes_view.py", line 120, in populateNodesView
>     if category is not None and category != CATEGORY_TO_ID[appliance["category"]]:
> KeyError: 'End devices'
> 
> 2018-08-20 21:45:17 WARNING crash_report:86 A .git directory exist crash report is turn off for developers. Instant exit
> 

Now, I cannot use GNS3. even after removing the appliance form "qemu appliances", still crashes when I click any device category.

**Comment by AJNOURI** [comment]
I've tried to reinstall both the server and the gui, but the crash persists.
Is there a way to remove the related template effect from the config, so at least I could carry on with gns3, until a solution is found?

----------------
Running GNS3 version 2.1.9 on Linux (64-bit) with Python 3.6.1 Qt 5.8.0 and PyQt 5.8.2.

**Comment by grossmj** [comment]
@AJNOURI Sorry for the delay, you should have created the issue on gns3-gui repository. I am going to look at it right away.

**Comment by grossmj** [comment]
I wonder how you managed to do this :/ One solution would be to edit the gns3_controller.conf and gns3_gui.conf files and look for the appliance name and edit the category field to put 0. Please backup these files first because it is easy to make a mistake and corrupt them.

**Comment by grossmj** [comment]
I pushed a fix, hopefully this fixes the problem.

**Comment by AJNOURI** [comment]
Removed all traces of the appliance from **gns3_controller.conf** .
Nothing related was in gns3_gui.conf .

Now I can, create labs, nodes and start the topology quasinormally, except of the message on the console log that doesn't seem to have any consequence:

> ****** Exception detected, traceback information saved in /home/ajn/.config/GNS3/exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.9-py3.6.egg/gns3/main_window.py", line 1000, in _browseEndDevicesActionSlot
>     self._showNodesDockWidget("End devices", Node.end_devices)
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.9-py3.6.egg/gns3/main_window.py", line 972, in _showNodesDockWidget
>     self.uiNodesDockWidget.populateNodesView(category)
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.9-py3.6.egg/gns3/nodes_dock_widget.py", line 63, in populateNodesView
>     self.parent().uiNodesView.populateNodesView(category, text)
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.9-py3.6.egg/gns3/nodes_view.py", line 120, in populateNodesView
>     if category is not None and category != CATEGORY_TO_ID[appliance["category"]]:
> KeyError: 'End devices'
> 
> /usr/local/lib/python3.6/site-packages/raven/conf/remote.py:88: UserWarning: Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.
>   warnings.warn('Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.')
> 
>

**Comment by grossmj** [comment]
This should be fixed now. Please comment if you face that issue again.
