### ISSUE TITLE
F5 ve Gtm/dns for gns3

### ISSUE THREAD

**Issue by pirusti** [GNS3/gns3-registry#364]
Hello there, 
is it possible to add at the marketplace the image of GTM/DNS in order to import it in gns3 lab environment? It would be really helpfull for me to have it since i would like to simulate the real network that we use at my company. 
Does it depends from F5 ?

Thank you in advance.

**Comment by adosztal** [comment]
Hi Ledio,

As far as I know the F5 products, every feature (LTM / GTM / WAF / etc.) runs on the same platform called BIG-IP, and it's up to you which module you choose to use.

The appliance file imports the image that contains all features (filename: `BIGIP-<version>.ALL.qcow2.zip`); hence the GTM should be already supported.

Please try to import this image.

**Comment by pirusti** [comment]
Correct, than i change my question: once i installed the bigip platform and i choose to use the GTM module , how does it works with the licenses. We don't need them, right?

**Comment by adosztal** [comment]
No, you'll need a license. However there are [trial licenses](https://www.f5.com/trials) available for testing.
