### ISSUE TITLE
[Feature Request]: Add Java & Java Webstart capabilities to webterm Docker image

### ISSUE THREAD

**Issue by fadlytabrani** [GNS3/gns3-registry#369]
Is it possible to have these capabilities built into the Docker image? It will be helpful in using the image for connecting to java-based management consoles.

**Comment by adosztal** [comment]
@ehlers, can you take a look at it? If I remember correctly, webterm is your baby. :)

**Comment by ehlers** [comment]
That's history. As there is no simple way to update a docker image in GNS3 (see <https://github.com/GNS3/gns3-registry/issues/145>), I think that docker appliances are not useful. Therefore I no longer support ipterm/webterm here in the registry. So maybe these appliances should be removed.

That doesn't mean, that I no longer like docker in GNS3, just distributing it through appliances is not end-user compatible, IMHO.

**Comment by adosztal** [comment]
From Bernhard:

> That's history. As there is no simple way to update a docker image in GNS3 (see #145), I think that docker appliances are not useful. Therefore I no longer support ipterm/webterm here in the registry. So maybe these appliances should be removed.
> 
> That doesn't mean, that I no longer like docker in GNS3, just distributing it through appliances is not end-user compatible, IMHO.

Let's close this issue for now, but we'll need to think how we move forward with container appliances.
