### ISSUE TITLE
Palo Alto Networks Firewall

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-registry#38]
https://community.gns3.com/docs/DOC-2114

**Comment by datboy12** [comment]
this link is dead, Could you please post it again or send me datboyaries@gmail.com
Many thanks!

**Comment by grossmj** [comment]
Apparently documents have not been migrated to our new website. We will investigate that.

**Comment by datboy12** [comment]
thank you ! i hope it will available soon because i'm studying about Palo Alto fire wall

**Comment by ehlers** [comment]
Found the page in the internet archive https://archive.org/index.php
It mainly consists of a pdf file "Connecting a VM Palo Alto Firewall to GNS3.pdf"

Via search engine I found this, which allows me to download it:
http://docslide.us/documents/connecting-a-vm-palo-alto-firewall-to-gns3pdf.html

**Comment by noplay** [comment]
A qcow2 exists:
https://www.paloaltonetworks.com/documentation/61/virtualization/virtualization/about-the-vm-series-firewall/vm-series-deployments.html

**Comment by cioby23** [comment]
I think this can be closed as a Palo Alto appliance exists in the Marketplace https://gns3.com/marketplace/appliance/pa-vm

**Comment by grossmj** [comment]
Indeed :+1:
