### ISSUE TITLE
Dell OS9/FTOS is not working: interface count and names does not correspond to template, no connectivity

### ISSUE THREAD

**Issue by TheNetworkIsDown** [GNS3/gns3-registry#380]
In fact, after deployment, the appliance contains the following interfaces:
Fo 0/0
Fo 0/4
Fo 0/8
...
up to Fo 0/124

So in total there are 32 interfaces, with a numbering step of 4, whereas the template suggests that there should be 6 in total, the first one being the (out-of-band) management interface.

I tried enabling all of them to see what could possibly be connected where but none came up.

BTW during the initial dialog in GNS3-GUI while adding the appliance, the description is mentioning Dell Networking OS10, whereas clearly we are talking about OS9/FTOS here.

**Comment by NeilHanlon** [comment]
@NotAProfessionalDeveloper Did you ever get this working? I've been at it for almost three days trying to get FTOS 9 running in GNS3. I can get the OS up, but despite getting link on one side, the dell side thinks there is no medium available and the ports will not come up :(

I've even tried in VirtualBox to no avail.

**Comment by dgcco175** [comment]
@NeilHanlon Did you ever figured out the magic sauce to get the DellOS9 appliance to function in GNS3? I am able to get communication when I make the interfaces layer 3 and issue the no keepalive command. I can't get links up when operating at layer 2. In fact, even if I create a VLAN interface and assign an IP address, nothing. 

I can see arp requests going outbound on the link but when I debug arp (all arp) on the remote side, I get no messages to the console.

**Comment by NeilHanlon** [comment]
Nope... I just gave up. Sorry @dgcco175

**Comment by dgcco175** [comment]
No worries. Thanks for the response!


Sent from Yahoo Mail for iPhone


On Thursday, May 28, 2020, 6:57 PM, Neil Hanlon <notifications@github.com> wrote:




Nope... I just gave up. Sorry @dgcco175
