### ISSUE TITLE
Updated cisco ISE appliance to include ISE2.3 and ISE2.4

### ISSUE THREAD

**Issue by nesselzzz** [GNS3/gns3-registry#395]
I have updated the Cisco ISE appliance to include ISE versions 2.3 and 2.4. Keep in mind that system requirements retrieved from Cisco's website state that a minimum of 16Gb of RAM, and 4vcpus are necessary to make it function. This turned out to be true as the appliance crashed in the middle of installing for me when testing with less resources than those minimum requirements. You can easily make those changes within the appliance template, after importing it. 

Also, it is imperative that your GNS3 VMDKs are of a sufficient size. I ran into an issue where the ISE install would crash because there wasn't enough space in my GNS3 VMDK. Use a program like Gparted to expand your VMDKs within the GNS3 VM, after increasing the hard drive space at the hypervisor level.

In the GNS3 documentation, it is mentioned to open an issue to add the updated GNS3 appliance to the repository. Please provide next steps. Thanks!

**Comment by adosztal** [comment]
Sorry, I didn't notice this thread. Here's a guide how to update appliances: https://adosztal.blogspot.com/2019/01/managing-gns3-appliances.html

As for the VM's disk size, I'll raise another issue in the GNS3 VM repo.
