### ISSUE TITLE
Brocade Virtual Traffic Manager

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-registry#42]
https://community.gns3.com/community/connect/community-blog/blog/2015/10/26/brocade-traffic-manager-qemukvm

**Comment by noplay** [comment]
For the moment the issue is the image size is 11G because it's a raw disk. But it can be convert to a qcow2 of 1.6G.

**Comment by adosztal** [comment]
I have the image and can create a template but should I convert it to qcow2? I can include the convert command in the usage string but it won't be as plug and play as it is with the raw image.

**Comment by noplay** [comment]
And I think two conversion could lead to different checksum :(

**Comment by adosztal** [comment]
Ok, I stick to the raw file then. It's eating up disk space but still better than nothing. :)

**Comment by adosztal** [comment]
Template in #142
