### ISSUE TITLE
Pi-hole

### ISSUE THREAD

**Issue by brentstewart** [GNS3/gns3-registry#425]
I thought I'd tackle building a docker appliance.  The one I'm interested in is pi-hole (https://github.com/pi-hole/docker-pi-hole).  I'm trying to use the other docker containers as a template, but I'm struggling.  Doesn't help that I'm learning Docker as I go.

Is there any documentation on building docker appliances?

Thanks.

**Comment by adosztal** [comment]
I learned from [other containers'](https://github.com/GNS3/gns3-registry/tree/master/docker) Dockerfiles and the [Dockerfile best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/).
