### ISSUE TITLE
Watchguard image?

### ISSUE THREAD

**Issue by R3n3r0** [GNS3/gns3-registry#443]
is it possible to integrate the image of a watchguard firewall?

**Comment by brentstewart** [comment]
I looked at https://www.watchguard.com and it looks like this product
requires a license.  If there's a free or trial version, I'm glad to give
it a try.

I suggest that you build the appliance yourself using a licensed image.
There's a sample gns3a file that shows how to do it, or just use one of the
other appliances as a template.  It's really not too hard.  I'm sure that
other WatchGuard users would appreciate it!


Regards,
Brent

**Comment by R3n3r0** [comment]
Which gns3 template do you recommend I look?

**Comment by brentstewart** [comment]
You can look at the Kali image, it's a good example.  Feel free to reach out to me directly if you have a question.  Looks like a cool project - good luck!

**Comment by R3n3r0** [comment]
Ok thanks you:)I'm informing myself to get a demo version of fireware os:)

**Comment by adosztal** [comment]
FireboxV and XTMv are now available.
