### ISSUE TITLE
Changed URL for Core-6.4.iso

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-registry#45]
With the release of TinyCore 6.4.1 the download location of .../release/Core-6.4.iso has changed to .../archive/6.4/Core-6.4.iso .

Affected files:
- packer/NETem/NETem.json
- packer/tinycore-linux/core-linux.json
- packer/tinycore-linux/core64-linux.json
- packer/tinycore-linux/tinycore-linux.json

So there are two options:
- change to Core-6.4.1
- change the URL to archive location

I suggest to change to the archive location of 6.4, otherwise on each new TinyCore version the ISO URL has be changed. Drawback is, of course, that the images are not build with the actual TinyCore version.

**Comment by noplay** [comment]
I agree with you it's better to target a fixe release

**Comment by noplay** [comment]
I will fix the files

**Comment by ehlers** [comment]
Same problem with CorePure64-6.4.iso in packer/tinycore-linux/core64-linux.json

**Comment by noplay** [comment]
Fixed
