### ISSUE TITLE
Remove NETem?

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-registry#462]
GNS3 v2.1 introduced packet filters, that obsoletes NETem. As GNS3 v2.1 was released almost 2 years ago, I think it's time to remove NETem.

Shall I create a PR, that removes NETem?

**Comment by grossmj** [comment]
Is there anything in NETem that GNS3 cannot do?

**Comment by grossmj** [comment]
One reason to keep NETem is that it could be more capable to filter lot of packets and seems to support more advance filters.

**Comment by b-ehlers** [comment]
I don't know, how good the performance of NETem is. I assume, that the filtering itself is quite good, as it's done in an (qemu emulated) Linux kernel. But you also have the overhead of two GNS3 links to/from the VM instead of one with the packet filter.

NETem can limit the bandwidth, something I haven't seen in the GNS3 packet filters. A more exotic feature of NETem is the possibility to create asymmetric filters. It should be possible to emulate that with BPF. Featurewise I think the packet filters are better because of the very general BPF feature.

**Comment by grossmj** [comment]
I would say just keep NETem just in case. It is good to have multiple ways to accomplish the same thing. There are always someone using something and who will complaint if we remove it (i.e. see what happened when we tried to remove legacy ASA support).

**Comment by b-ehlers** [comment]
Just tested the performance. Using two docker VMs (these very fast) and NETem/packet filter.

| Filter              | Performance (iperf)  | Delay (ping) |
| ------------  | --------------------: | ------------: |
| None             |                1030 MBit/s |           0.2 ms | 
| NETem          |                   119 MBit/s |           1.2 ms |
| Packet Filter |                  726 MBit/s |           0.2 ms |

The packet filter are remarkably fast, much faster as NETem. So performance is no reason to keep NETem.

For me the main reason to keep NETem is the bandwidth limitation feature.

As NETem needs no maintenance, lets keep it.

Closing the issue...

**Comment by grossmj** [comment]
Thanks for testing the performance. Very nice to see that packet filter is fast :)

**Comment by b-ehlers** [comment]
Yes, I was pleased as well. BTW in both cases I configured a packet loss rate of 0.1%. That way the filter was active, but didn't drop any packet during the measurement.
