### ISSUE TITLE
Use GitHub package registry to publish Docker images

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-registry#468]
Need to research this: https://help.github.com/en/github/managing-packages-with-github-package-registry/configuring-docker-for-use-with-github-package-registry

**Comment by b-ehlers** [comment]
I created a demo repository <https://github.com/b-ehlers/gns3-docker-images>, that uses GitHub Actions to build Docker images and publish them on the GitHub Docker Registry. By changing the arguments to the docker login action in [.github/workflows/build.yml](https://github.com/b-ehlers/gns3-docker-images/blob/master/.github/workflows/build.yml) it should be also possible to push the Docker images to the "normal" DockerHub, but I haven't tested this.

The build system in [.github/bin/build](https://github.com/b-ehlers/gns3-docker-images/blob/master/.github/bin/build) rebuilds an image only, when the subdirectory containing the Dockerfile has changed, or its base image has been updated.

Interested?

**Comment by grossmj** [comment]
Looks good. Definitely interested :)

**Comment by b-ehlers** [comment]
Here some more information about the build system [.github/bin/build](https://github.com/b-ehlers/gns3-docker-images/blob/master/.github/bin/build):

It is written in Python, so it should be easier to understand, than a complicated shell script.

When running it without an argument it checks for each image if the directory containing its Dockerfile has changed or its base image has been updated. To check for changes of the build instructions the build system needs the full git history. As the size of this repository is quite small, that should be fine. Alternatively the Docker build files could be moved to a repository of its own. 

For testing, if the base image has changed, I need the information about the image layers. As I haven't found a tool, that retrieves this information directly from the docker registry, the build system queries the registry using the API. This is the most difficult part of the build system, where bugs may arise.

In some special cases a docker image needs a forced rebuild. For that a tag can be created, that contains the list of images, joined by an underscore and beginning with an underscore. For example, if images abc and def should both be rebuild, create the tag `_abc_def`. The underscore at the beginning was choosen to allow the use of "normal" tags, that won't interfere with the build system.

The special image name "all" will forcely rebuild all images. If additional images will follow "all", these images will be skipped. For example the tag `_all_abc` will rebuild all images except abc.

These special tags should allow to deal with situations, where a forced rebuild is needed. But that should be great exceptions.

**Comment by b-ehlers** [comment]
Just switched to using base image names (e.g. ipterm), previously the full image name including registry and username (e.g. ghcr.io/b-ehlers/ipterm) has to be used. The build system now uses the environment variable DOCKER_ACCOUNT, it must contain the registry and username.

This makes the build system a bit more complex. But it's now far easier to move to a different registry, using a different username or building the images locally.

**Comment by grossmj** [comment]
Thanks again for sharing this. I will focus on it once we release GNS3 v3.0 :)

**Comment by b-ehlers** [comment]
I know, GNS3 2.0 is not yet released. I just want to share my current knowledge.

Docker supports any repository, that implements <https://docs.docker.com/registry/spec/api/>. To use a non-DockerHub repository you just need to insert its hostname. For example `ghcr.io/b-ehlers/ipterm` refers to the ipterm image of user b-ehlers in the GitHub container registry ghcr.io. All Docker applications, including GNS3, support this extended scheme.

To push an image to a repository, first you have to login with `docker login`. Then issue a series of `docker build` and `docker push` to build and push your images. When the support for multiple architectures is needed, `docker buildx build` should be used instead. The simplest way would be to put these commands in a script file and execute it, when needed. That script may run on a local computer or in the cloud.

DockerHub has a build system, that makes it quite easy to build and publish images. But this services requires a payed subscription since mid 2021. For occasional use, it is probably too expensive. So also on DockerHub `docker push` is the way to go.

Both a script and the DockerHub build system has the disadvantage, that it takes quite some time to build all images. Typically it is run on any change in the GitHub repository, even when the Dockerfiles are not changed. To improve that, I created a Docker build system, that builds only the images that changed. Details can be found at <https://github.com/b-ehlers/gns3-docker-build/blob/master/docker_build.md>. It works with any Docker registry. I have tested it with DockerHub and the GitHub container registry ghcr.io. It should run on any system, that supports Python. It was tested locally and with GitHub Actions.

**Comment by grossmj** [comment]
> But as the milestone of 3.2 is years ahead, I won't hurry. When the time has come for implementation, feel free to contact me.

I think we should prioritize this issue and add implement something on GitHub Actions to automatically build and push Docker containers when needed. For now we can push to Docker Hub and then later, GitHub packages as well.

**Comment by grossmj** [comment]
> So how can I help? I suggest, that I use my old gns3-docker-build code and create a fork of this registry (and optionally a PR). This gives you a build system using GitHub Actions, that rebuilds the docker images, that are changed or their base image were changed, and upload the images to a registry. You can then test it and make any changes you like. In a second step this build system could be enhanced to support uploading to multiple registries.

Your old gns3-docker-build code is not accessible anymore. Also, you mentioned [python-dxf](https://pypi.org/project/python-dxf/) and that your first tests were promising. How close the implementation is ready to be used?

> Alternatively rebuilding all images on any change is even simpler. Create a simple build script and run that via GitHub actions. This needs a longer build time and more CPU time. And it would run on any change in this registry, even when non-docker appliances are changed. But as long as you are not charged for GitHub Actions it doesn't matter.

That could be a solution. I am not too sure about not being charged for GitHub Actions, I think we get like 2000 minutes free per month? I would have to check. I just prefer something that build only if needed because it is more elegant... Alternatively, we could also have a manual GitHub Action trigger to rebuild and push the images similar to what we have to refresh and publish the API documentation for v3: https://github.com/GNS3/gns3-server/actions/workflows/publish-api-documentation.yml

**Comment by grossmj** [comment]
> My main issue is, who will support this? Of course, I will be in charge. But what happens, when I loose interest, lets say in 2 years? Are you willing to take over? If yes, fine, lets go that way. If no, it's better to use the simple brute-force solution.

No worries, we can support this 👍

**Comment by b-ehlers** [comment]
Well, I am faster than expected.

I created a fork [b-ehlers/gns3-registry-docker](https://github.com/b-ehlers/gns3-registry-docker) with the build system added. First I used it to upload to the GitHub Container Registry [ghcr.io](https://github.com/b-ehlers?tab=packages), then I changed the workflow to upload to [DockerHub](https://hub.docker.com/u/ehlers). So both registries are tested.

Some docker appliances need a dummy layer to get an updated container timestamp, I have updates those. But there are a lot of docker appliances, that are outdated or can't be built, see the comments in [docker/docker_images](https://github.com/b-ehlers/gns3-registry-docker/blob/master/docker/docker_images). So there is a lot to do.

The build system supports multi-platform build, for testing I enabled it for ovs-snmp. But that results in longer build times. Depending on the popularity of the Apple Silicon platform you can enable it for more appliances. But it requires, that the base image also supports the platform linux/arm64.

If you want to test it in your repository:

For an upload to ghcr.io you have to grant read/write permissions to GITHUB_TOKEN (Registry Settings / Actions / General/Workflow permissions / Read and write permissions).

For an upload to DockerHub you have to create an access token in DockerHub with read/write/delete permissions (Account Settings / Security / New Access Token). Then in the GitHub registry settings (Registry Settings / Secrets and variables / Actions / New repository secret) add 2 repository secrets, "DOCKERHUB_USERNAME" containing the DockerHub username and "DOCKERHUB_TOKEN" containing the DockerHub access token.

So how to go on? Do you want to have a look first? Or shall I create a PR and you decide them.

**Comment by grossmj** [comment]
Awesome, I think you can go ahead and create a PR.

Just one question, do you rebuild the images on a.schedule too?

```
  schedule: 
     - cron: '37 7 * * 3'
```

Thanks a lot 👍

**Comment by b-ehlers** [comment]
> Just one question, do you rebuild the images on a.schedule too?
> 
> ```
>   schedule: 
>      - cron: '37 7 * * 3'
> ```

Yes, there are 3 ways a rebuild is triggered:
* on push: The standard way, someone pushes to the master or (the not yet existing) main branch.
* on schedule: That's for checking if a base image has changed.
* manually: For the (hopefully rare) cases, when a forced rebuild is needed. For example, when there is an important update in some of the packages the image installs, but neither the Dockerfile nor the base image has changed.

**Comment by grossmj** [comment]
I had a quick review, excellent work on the Docker build system 👍 

To enable ghcr.io, do I just need to remove the comments on the following lines?

https://github.com/GNS3/gns3-registry/pull/767/files#diff-2817fc9ec6443e19233164eefa86576a0972ce81bcf0ec4a04f96d6119db038eR39-R40

https://github.com/GNS3/gns3-registry/pull/767/files#diff-2817fc9ec6443e19233164eefa86576a0972ce81bcf0ec4a04f96d6119db038eR51-R52

Thanks again.

**Comment by b-ehlers** [comment]
> To enable ghcr.io, do I just need to remove the comments on the following lines?
>
> https://github.com/GNS3/gns3-registry/pull/767/files#diff-2817fc9ec6443e19233164eefa86576a0972ce81bcf0ec4a04f96d6119db038eR39-R40
>
> https://github.com/GNS3/gns3-registry/pull/767/files#diff-2817fc9ec6443e19233164eefa86576a0972ce81bcf0ec4a04f96d6119db038eR51-R52

Almost.

Currently the lines for DockerHub are added twice, one time uncommented (and therefore active) and one time commented.

So I would remove the active lines 35-36 and 48:

https://github.com/GNS3/gns3-registry/pull/767/files#diff-2817fc9ec6443e19233164eefa86576a0972ce81bcf0ec4a04f96d6119db038eR35-R36

https://github.com/GNS3/gns3-registry/pull/767/files#diff-2817fc9ec6443e19233164eefa86576a0972ce81bcf0ec4a04f96d6119db038eR48

... and then uncomment the lines you mentioned.

Uncommenting the DOCKER_PASSWORD line (currently line 52) is optional. It's only needed, when you are using a private repository. But it doesn't hurt, when it is uncommented on public repositories. The drawback enabling it is, that the python script knows about the password.

Please note https://github.com/GNS3/gns3-registry/issues/468#issuecomment-1565587503:

> For an upload to ghcr.io you have to grant read/write permissions to GITHUB_TOKEN (Registry Settings / Actions / General/Workflow permissions / Read and write permissions).

**Comment by b-ehlers** [comment]
I have to agree, that this part of the workflow file is confusing. Hopefully the following changes makes it clearer.

This diff keeps to upload the images to DockerHub

```
diff --git a/.github/workflows/build-docker-images.yml b/.github/workflows/build-docker-images.yml
index cf678b1..fd20e7e 100644
--- a/.github/workflows/build-docker-images.yml
+++ b/.github/workflows/build-docker-images.yml
@@ -32,26 +32,26 @@ jobs:
         # https://github.com/marketplace/actions/docker-login
         uses: docker/login-action@v2
         with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
           # GitHub Container Registry:
           # registry: ghcr.io
           # username: ${{ github.repository_owner }}
           # password: ${{ secrets.GITHUB_TOKEN }}
+          #
           # DockerHub:
-          # username: ${{ secrets.DOCKERHUB_USERNAME }}
-          # password: ${{ secrets.DOCKERHUB_TOKEN }}
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
       - name: Install python requirements
         run: python3 -m pip install --requirement .github/bin/requirements.txt
       - name: Build and push images
         env:
-          DOCKER_ACCOUNT: ${{ secrets.DOCKERHUB_USERNAME }}
           # DOCKER_PASSWORD is optional, only needed for private repositories
+          #
           # GitHub Container Registry:
           # DOCKER_ACCOUNT: ghcr.io/${{ github.repository_owner }}
           # DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
+          #
           # DockerHub:
-          # DOCKER_ACCOUNT: ${{ secrets.DOCKERHUB_USERNAME }}
+          DOCKER_ACCOUNT: ${{ secrets.DOCKERHUB_USERNAME }}
           # DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
           #
           IMAGES: ${{ inputs.images }}
```

If you want to upload to the GitHub container registry comment the statements in the DockerHub section and uncomment the Github container registry statements.

A diff to the original file would than look like that:

```
diff --git a/.github/workflows/build-docker-images.yml b/.github/workflows/build-docker-images.yml
index cf678b1..dbfd9f2 100644
--- a/.github/workflows/build-docker-images.yml
+++ b/.github/workflows/build-docker-images.yml
@@ -32,12 +32,11 @@ jobs:
         # https://github.com/marketplace/actions/docker-login
         uses: docker/login-action@v2
         with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
           # GitHub Container Registry:
-          # registry: ghcr.io
-          # username: ${{ github.repository_owner }}
-          # password: ${{ secrets.GITHUB_TOKEN }}
+          registry: ghcr.io
+          username: ${{ github.repository_owner }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+          #
           # DockerHub:
           # username: ${{ secrets.DOCKERHUB_USERNAME }}
           # password: ${{ secrets.DOCKERHUB_TOKEN }}
@@ -45,11 +44,12 @@ jobs:
         run: python3 -m pip install --requirement .github/bin/requirements.txt
       - name: Build and push images
         env:
-          DOCKER_ACCOUNT: ${{ secrets.DOCKERHUB_USERNAME }}
           # DOCKER_PASSWORD is optional, only needed for private repositories
+          #
           # GitHub Container Registry:
-          # DOCKER_ACCOUNT: ghcr.io/${{ github.repository_owner }}
+          DOCKER_ACCOUNT: ghcr.io/${{ github.repository_owner }}
           # DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
+          #
           # DockerHub:
           # DOCKER_ACCOUNT: ${{ secrets.DOCKERHUB_USERNAME }}
           # DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
```

As stated in the comments, the DOCKER_PASSWORD statement is optional, it's only needed for private docker repositories. It doesn't hurt, when it gets enabled on public docker repositories.

For using the GitHub container registry see https://github.com/GNS3/gns3-registry/issues/468#issuecomment-1565587503:
> For an upload to ghcr.io you have to grant read/write permissions to GITHUB_TOKEN (Registry Settings / Actions / General/Workflow permissions / Read and write permissions).
