### ISSUE TITLE
Configure network interface on ubuntu container

### ISSUE THREAD

**Issue by Quixus** [GNS3/gns3-registry#486]
In the Ubuntu docker container I edited /etc/network/interfaces to give the interfaces the right static IPs but I cannot apply this change to to the appliance. Whatever command I enter to restart the interfaces I get a command not found error.

How can I set the IP Addresses of the interfaces in the container.

Thanks in advance.

**Comment by adosztal** [comment]
You need to set it outside the CLI, before starting the node. Right click on it --> Configure --> Edit network settings --> Change it just like you were editing `/etc/network/interfaces`.

**Comment by Quixus** [comment]
Thanks, that did the trick. Unfortunately Another problem arose. the container is connected to a cloud with one of the physical interfaces of the machine gns3 runs on. This interface is connected to a different physical computer. Now from that other computer I can ping the container through that physical interface , but the container cannot ping the other computer. What am I doing wrong?

**Comment by adosztal** [comment]
That has nothing to do with GNS3 or the containers. Check [this thread](https://www.gns3.com/community/discussion/cannot-ping-local-host-from-gns3) for the explanation.
