### ISSUE TITLE
Remove name from appliances?

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-registry#49]
I'm not sure if name and and product_name are not the exact same fields.

**Comment by noplay** [comment]
In GUI we use both fields.

**Comment by noplay** [comment]
It was shipped like that we can't change it easily.

**Comment by adosztal** [comment]
Though this was closed, I'd like to discuss it. The "product_name" is not used anywhere and, in most of the cases, is the same as "name". So we should keep "name" and remove "product_name" in a later registry version (obviously only when changing something else on the schema too, not on its own).
