### ISSUE TITLE
No Updates on Docker Registry since 2019-01-23

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-registry#491]
The (very few) updates of the docker appliances don't make it to the docker registry <https://hub.docker.com/u/gns3>, the last update on Docker Hub was on 2019-01-23. Some appliances are even older, network_automation is last updated on 2018-04-05, others are even 3 years old.

**Comment by grossmj** [comment]
I agree Docker hub has been neglected. I will check what we could do about this soon.

**Comment by adosztal** [comment]
The containers that I created there can be removed. The appliances are pointing to my repo.

**Comment by b-ehlers** [comment]
Some cleanup could be done as well, even though that was not the initial intention of this issue.

@adosztal That's `network_automation` and `python-go-perl-php`, right?

Additionally the following docker images seem to be not used by any appliance:
- dhcp
- endhost
- haproxy
- iou
- network_automation_pycharm
- snmpsimulator
- xeyes

`dhcp`, `iou` and `xeyes` are experiments, `endhost` might be used by @AJNOURI, they may be kept. But the others could be candidates for deletion.

**Comment by adosztal** [comment]
Correct, I created those two.

**Comment by b-ehlers** [comment]
The primary issue, that the docker registry wasn't updated, is solved. So I will close this issue.

Nevertheless a lot of docker containers need some care, most of them are outdated. But I suggest to discuss that in appliance specific issues.
