### ISSUE TITLE
Huawei NE40

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-registry#497]
Tentative to support Huawei NE40: https://gns3.com/community/discussion/gns3-and-huawei-ne40

**Comment by grossmj** [comment]
Now we can use the Huawei NE40 appliance as described in https://gns3.com/community/discussion/gns3-and-huawei-ne40

We could create a Cloud node with the correct UDP tunnels already configured. We could have a script automatically executed too when we do support it in GNS3.

**Comment by aridhaa** [comment]
Hi team,
Could you create a built-in Cloud with : 

- script field where we can add a script to run windows CMD to start the router (**vboxmanage startvm HUAWEI --type headless**)
- start/stop buttons to run script that start/stop the router

UDP tunnels and console with telnet already exist :)
BR
Ridha

**Comment by jrszoio** [comment]
Guys, i can't access the previews discussion on this link:  https://gns3.com/community/discussion/gns3-and-huawei-ne40

Someone could say what happened?  Tks.

**Comment by aridhaa** [comment]
It seems that GNS3 team is not interested in this section, no feedback from them since June despite I did all the hard job.

**Comment by grossmj** [comment]
> Guys, i can't access the previews discussion on this link: https://gns3.com/community/discussion/gns3-and-huawei-ne40

Weird, maybe one of our moderator has deleted it... I will see if we can recover that.

> It seems that GNS3 team is not interested in this section, no feedback from them since June despite I did all the hard job.

We are interested but the Huawei NE40 is not really user friendly to install, I know we can use it via a cloud but this doesn't really fit our appliance installation process at this time. However, we have recently added the NE40 appliance https://github.com/GNS3/gns3-registry/blob/master/appliances/huawei-ne40e.gns3a but it is up to users to create the Qemu image, the same as EVE-NG.

**Comment by fernandolcx** [comment]
I'm testing the new CE12800 image, some basic stuff appears to work fine except when using VLANs.
There's also a problem with interface naming in the appliance config but this I can fix myself.

> > Guys, i can't access the previews discussion on this link: https://gns3.com/community/discussion/gns3-and-huawei-ne40
> 
> Weird, maybe one of our moderator has deleted it... I will see if we can recover that.

Have you figured out what happened?

**Comment by fernandolcx** [comment]
Well, I've manually added a static ARP entry poiting to their dot1q subinterface and it worked.

**Comment by jrszoio** [comment]
Thank you! I hope everyone it's fine!

Can you say a little bit more about your implementation? Step-by-step... please!


________________________________
De: Fernando Chaves <notifications@github.com>
Enviado: segunda-feira, 11 de janeiro de 2021 00:55
Para: GNS3/gns3-registry <gns3-registry@noreply.github.com>
Cc: José Rodrigo dos Santos <joserodrigo@gec.inatel.br>; Comment <comment@noreply.github.com>
Assunto: Re: [GNS3/gns3-registry] Huawei NE40 (#497)


Well, I've manually added a static ARP entry poiting to their dot1q subinterface and it worked.

**Comment by wevertonjlima** [comment]
Hi .... I am looking for Huawei CE 12800 images (qwco2) for GNS3... any tips where I can download?
