### ISSUE TITLE
Appliance symbols

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-registry#5]
How should we handle the appliance symbols?

Currently in GNS3 we have built-in symbols and custom ones. When a user adds a device that has a custom symbol, this symbol is copied to the project directory so the project can be easily shared. We do not have a local directory to store custom symbols.

Should we assume that for all appliance we add, we have a built-in symbol in GNS3? Like done in:
https://github.com/GNS3/gns3-registry/blob/master/devices/cumulus-vx.json#L13

This is the most simple solution.

We could also have symbol files that come with the appliance images... This could be an option, if no custom symbol is provided we revert back to the default built-in symbol specified in the json file.

**Comment by noplay** [comment]
What did you think of my solution? Adding a symbol url in the JSON and we download the file if not on disk when installing the appliance.

And we host the symbols in our Github repository.

**Comment by noplay** [comment]
We will put a symbol name in the file and fallback to default symbol if can not download
