### ISSUE TITLE
Import vEOS-lab-4.23.0.1F.vmdk got md5 error, unable to load the vmdk.

### ISSUE THREAD

**Issue by clouds-river** [GNS3/gns3-registry#500]
Try to import 4.23.0.1F version vEOS, even after I ignore the checksum, I am unable to import this VMDK. 

  "md5sum": "08d52154aa11a834aef9f42bbf29f977",   <--  This maybe need updated.

Also the file name is not same as the arista download site.

"filename": "vEOS-lab-4.23.0.1F.vmdk",    <--

vEOS-lab-4.23.1F.vmdk   <-- Arista download site filename.

**Comment by Gelob** [comment]
4.23.0.1F and 4.23.1F are actually different versions. You grabbed a newer version than whats currently in the GNS3 repository.

**Comment by Gelob** [comment]
@grossmj can you close this out?

**Comment by clouds-river** [comment]
> @grossmj can you close this out?

Sure, thanks.
