### ISSUE TITLE
Add download/unpack instructions to some appliances

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-registry#506]
For some appliances it's difficult for an non-expert to download and unpack the images. Sometimes it's difficult to find the image on the web site, sometime you need a registration. Sometimes some additional steps are necessary after the download to get the image. An example is the WatchGuard FireboxV appliance.

In some cases the usage instructions are giving some hints, but these are shown in GNS3 after the image is sucessfully imported, that's too late. So I suggest to add a download description field to those appliances, where downloading the image is not that easy. These instructions should be available in GNS3 in the appliance import wizard while selecting an image file.

**Comment by b-ehlers** [comment]
There is already an "compression" property to warn the user, that the downloaded file  needs uncompression. That's a good start, but it covers only some basic postprocessing needs.

**Comment by eantowne** [comment]
So maybe an "Installation instructions" field in addition to the "Usage Instructions"?

**Comment by grossmj** [comment]
I am going to add this appliance version 8 format: https://github.com/GNS3/gns3-registry/issues/734
