### ISSUE TITLE
PA-VM-KVM

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-registry#510]
Does PA-VM-KVM need more options to successfully boot?

https://gns3.com/community/discussion/pa-vm-kvm9-0-4-goes-to-booting-a

**Comment by adosztal** [comment]
> Reason: Requires at least **4.0GB** of memory for PA-VM nolic license, **2.0GB available**.

I wouldn't change boot options just to run it with less memory. Even if it boots, we can't guarantee that it won't crash later on.
