### ISSUE TITLE
Can't open Jupiter container console

### ISSUE THREAD

**Issue by taniokaeiji** [GNS3/gns3-registry#520]
I'm Running: GNS3 2.2.8 with VM 2.2.8.

I want to run Jupyter container on GNS3, so Add from "New templates".
Then all done, and start container, can't access Jupyter's console.

I got Dockerfile and jupyter_notebook_config.py from GNS3/gnse-registry/docker/jupyter.
Then run "docker build -t jupyter ." but displays red line:
>You are using pip version 9.0.1, however version 20.1.1 is available.
>You should consider upgrading via the 'pip install --upgrade pip' command.

So I will change python version tag from 3.6.1 to 3.7.7, then no RED line.

But run "docker run -p 8888:8888 jupyter", jupyter does not start. Log says:
> OSError: [Errno 99] Cannot assign requested address

It seems ip binding error, so add this line in jupyter_notebook_config.py:
`c.NotebookApp.ip = '0.0.0.0'`

Then "docker build" and "docker run" success.

Is this fix correct?
Or should I create pull request about is?

Regards,

**Comment by grossmj** [comment]
> Or should I create pull request about is?

Please go ahead and create a pull request.

**Comment by grossmj** [comment]
I have rebuilt the Docker image on Docker hub: https://hub.docker.com/r/gns3/jupyter/builds

I tested it in GNS3 and it worked.

Thanks again for your contribution! :+1:
