### ISSUE TITLE
vSRX3 Appliance

### ISSUE THREAD

**Issue by yzguy** [GNS3/gns3-registry#569]
Looks like the vSRX appliance is the 1.0 version, and boots incredibly slow. I believe it has an embedded RE VM in it. After some searching about it, people mentioned the vSRX 3.0. [Differences between vSRX and vSRX 3.0](https://kb.juniper.net/InfoCenter/index?page=content&id=KB33572)

It would be good to either add vSRX 3.0 to the vSRX appliance file, or to create a new vSRX 3.0 appliance.
Either way, I'd like to put this together, just looking for some guidance on whether to combine with vSRX or make a vSRX 3.0

Configuration-wise they are the same, so it's basically a copy+paste, change images + versions.

**Comment by grossmj** [comment]
@yzguy I think we can just add images + versions to the current vSRX if they are the only differences.

We accept pull requests to create or make changes to appliance files. Let me know if you can do this. Thanks :+1:

**Comment by yzguy** [comment]
I would love to do this, just wanted to see thoughts on new file versus addition to existing. I'll get a PR up for the vSRX 3.0 additions. Thanks!

**Comment by grossmj** [comment]
@yzguy thanks, I will wait for your PR :+1:
