### ISSUE TITLE
Fortigate

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-registry#58]
https://gns3.com/discussions/fortigate-vm-on-gns3-ver-1-4-lin

**Comment by noplay** [comment]
@adosztal has made a tutorial https://www.linkedin.com/pulse/running-fortigate-qemu-vm-gns3-andras-dosztal

We just need to transform it to an appliance for the marketplace.

**Comment by adosztal** [comment]
I'll get the latest 5.2 & 5.4 images and create the .gns3a file. Will share the empty disk image as well.

**Comment by noplay** [comment]
I put the empty image on sourceforge

MD5: 3411a599e822f2ac6be560a26405821a
Filesize: 197120

```json
        {
            "filename": "empty30G.qcow2",
            "version": "1.0",
            "md5sum": "3411a599e822f2ac6be560a26405821a",
            "filesize": 197120,
            "download_url": "https://sourceforge.net/projects/gns-3/files/Empty%20Qemu%20disk/",
            "direct_download_url": "http://downloads.sourceforge.net/project/gns-3/Empty Qemu disk/empty30G.qcow2"
        }
```

**Comment by noplay** [comment]
I'm lost in the fortigate website :P If you can share a link to the page on their site where I can get the 15 day trial.  I have register an account.

**Comment by noplay** [comment]
Ok it's  https://support.fortinet.com/Download/FirmwareImages.aspx but work only for fortigate customers.

**Comment by adosztal** [comment]
If you're not a partner: https://support.fortinet.com/Download/FirmwareImages.aspx
If you're a partner, you have to access the download page through the partners portal: https://partners.fortinet.com, then Support -> Online support -> Download -> Firmware images

There are no direct links, navigation to the firmware images is done using JavaScript functions on one huge ASPX page... [opinion removed :)]

**Comment by adosztal** [comment]
Hmm... is it possible to start interface numbering from 1? "port_name_format": "port{0}" starts from Port0 but FortiGate start numbering at Port1.

**Comment by noplay** [comment]
perhaps "port_name_format": "Port{1}"

**Comment by adosztal** [comment]
Already tried that, I receive this error message: "The format must contain at least {0}, {port0} or {port1}"

**Comment by noplay** [comment]
After reading the code port1 should work. It seem {0} and {port0} is the
same is it right @grossmj?

**Comment by Melkske** [comment]
Hello can some post me the link to the firmware?
FortiGate 5.4.4

**Comment by noplay** [comment]
You can get it from Fortigate if you are a customer.
