### ISSUE TITLE
Issues with packer versions

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-registry#584]
I just tried to use packer to create an image, when I noticed, that it behaves differently depending on the version.

Starting with v1.6.0 packer doesn't accept packer files, that use the `iso_checksum_type`. Packer up to v1.3.x requires this option. Packer v1.4.x and v1.5.x work with and without `iso_checksum_type`. Ubuntu since 20.04 (focal) including the latest 21.04 (hirsute) uses packer v1.3.4, therefore it might be best to include `iso_checksum_type`, but more recent packer versions will fail building the image.

Packer v1.6.3 - v1.6.6 have a bug <https://github.com/hashicorp/packer/issues/10211>, that breaks the build, when disk_interface ide is used. A workaround is using disk_interface virtio-scsi, successfully tested with the alpine packer files, but that might not work with other images. Best, of cause, is using packer versions up to v1.6.2 or 1.7.0 and above.

So using packer becomes a bit more difficult, either we have to use a specific version to build our images, or we need to create slightly different receipts for different packer versions (and have to test them with these versions).

**Comment by b-ehlers** [comment]
> Packer v1.6.3 - v1.6.6 have a bug hashicorp/packer#10211, that breaks the build, when disk_interface ide is used.

Created a bug report for Debian Bullseye <https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=987932>, so hopefully this bug will be fixed some day in Debian/Ubuntu.

**Comment by b-ehlers** [comment]
> > Packer v1.6.3 - v1.6.6 have a bug [hashicorp/packer#10211](https://github.com/hashicorp/packer/issues/10211), that breaks the build, when disk_interface ide is used.
> 
> Created a bug report for Debian Bullseye https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=987932, so hopefully this bug will be fixed some day in Debian/Ubuntu.

The Debian devs have backported the fix, currently the fixed version is in unstable. As bullseye is currently in freeze, it may take a some time until bullseye is upgraded too, but eventually it will happen.

I have checked the version other Linux variants are using: <https://pkgs.org/download/packer>.

Ubuntu stil uses v1.3.4. If they decide to upgrade to v1.6.6, I'm confident they will use the Debian patches. Alternatively Ubuntu may use v1.7.x, where this bug is fixed. So in any case future packer updates in Ubuntu should be fine.

The other Linux variants use either a version older than v1.6.3 or they use v1.7.x, so they are not affected as well.

So the second part of this issue is done. That leaves only the issue with the `iso_checksum_type`. Maybe adding a note in the READMEs to remove this option with packer versions >= v1.6.0 might be sufficient.

**Comment by grossmj** [comment]
> That leaves only the issue with the iso_checksum_type. Maybe adding a note in the READMEs to remove this option with packer versions >= v1.6.0 might be sufficient.

I am happy to accept a PR to change the READMEs. Thanks :+1:
