### ISSUE TITLE
Kali linux appliance needs an update

### ISSUE THREAD

**Issue by gustavoberman** [GNS3/gns3-registry#585]
Hi there,
Today I wanted to try the kali linux guest image, but the *iso images in appliances/kali-linux.gns3a are old and no longer available at http://cdimage.kali.org/. Instead they are at http://old.kali.org/kali-images/
What's the procedure to update this? 
Not just the links, also make available newer versions. 
Thanks!

**Comment by gustavoberman** [comment]
I opened an Pull Request  #586  with the modifications of existing ISOs in new URLs

**Comment by grossmj** [comment]
You can create a pull request to update https://github.com/GNS3/gns3-registry/blob/master/appliances/kali-linux-cli.gns3a and https://github.com/GNS3/gns3-registry/blob/master/appliances/kali-linux.gns3a

The content should be pretty clear, just make sure the md5 checksum, filesize and links are correct. Thanks :+1:

**Comment by grossmj** [comment]
> I opened an Pull Request #586 with the modifications of existing ISOs in new URLs

Sorry, I haven't seen you already created a PR. I merged it, thanks :+1:

**Comment by grossmj** [comment]
Please feel free to create another PR to add more recent versions too. Thanks.
