### ISSUE TITLE
Verified field for appliance files

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-registry#622]
Add an "official" or "verified" field to each appliance files and display a warning when an user wants to install an unofficial / unverified appliance.

**Comment by eantowne** [comment]
What would be the criteria for "verified", and who does it?

**Comment by grossmj** [comment]
Well, I don't think we need it anymore. This was before we added a policy for accepting new appliances: https://github.com/GNS3/gns3-registry#policy-for-new-appliances
