### ISSUE TITLE
Create reproducible ISO images?

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-registry#641]
Currently the ISO images in the cloud-init directory are not build reproducibly, for example some timestamps are changing on every build. So there is no simple way to verify the images.

I have not found a simple receipt to create a reproducible ISO, for example <https://reproducible-builds.org/docs/system-images/> gives only some advise, but nothing that can be easily implemented.

After some experimentation I got the following receipt, that should work:

Here an example for the Debian cloud-init ISO

```
export SOURCE_DATE_EPOCH=$(date +%s -u -d 2022-01-02T09:00:00)
xorriso -volume_date all_file_dates =${SOURCE_DATE_EPOCH} -preparer_id XORRISO \
        -as mkisofs -output debian-cloud-init-data.iso -volid CIDATA -joliet -rock user-data meta-data
```

* `mkisofs`/`genisoimage` seem not to be able to create reproducible images, `xorriso` seems the way to go.
* The `SOURCE_DATE_EPOCH` environment variable sets the date for the meta data, but not for the files. As git doesn't preserve file dates, I use the option `-volume_date all_file_dates =${SOURCE_DATE_EPOCH}` to set the file dates to  SOURCE_DATE_EPOCH.
* `xorriso` sets it's name, version and some build info into the data preparer id of the ISO volume descriptor. As this is different in every xorriso build, I set a fixed value with `-preparer_id XORRISO`.

I'm still not an expert for creating reproducible ISO images, but I'm confident that I addressed the main issues.

For anyone to verify, here the image (zipped) [debian-cloud-init-data.zip](https://github.com/GNS3/gns3-registry/files/7798907/debian-cloud-init-data.zip), the MD5 is `eafe1f9220d04191cb1a19f2255b63f9`.

@grossmj Do you think, we should use reproducible ISO images? It's great to generate the same image, when using the same input. But it also needs some effort. The creator needs to install xorriso and set SOURCE_DATE_EPOCH. Furthermore my receipt needs some testing, if it really creates the same image on every system.

**Comment by b-ehlers** [comment]
I have reconsidered it, it's too much effort for a limited benefit.

**Comment by grossmj** [comment]
While interesting, I agree, too much effort for little benefits :+1:
