### ISSUE TITLE
CML (VIRL) version of ASAv9.16.2 has different MD5sum than the full version, how to add to registry?

### ISSUE THREAD

**Issue by eantowne** [GNS3/gns3-registry#678]
The Cisco Modeling Labs (used to be called VIRL) version of ASAv9-16-2.qcow2 has a different md5sum than the full version referenced in the registry file. They both have the same filename, how would this be handled?

Obviously the "version" would be modified to include "CML" or "VIRL" similar to the CSR1000v, but how to handle the actual files having the same names?

Full version (in appliance file registry already):
"filename": "asav9-16-2.qcow2"
"md5sum": "c3aa2b73b029146ec345bf888dd54eab"

CML 2.4.0 version of file:
"filename": "asav9-16-2.qcow2"
"md5sum": "1f8db97063a7f738fddc81ac880a906c"

**Comment by grossmj** [comment]
Do they have the same size? It is possible that the one referenced in the appliance file is wrong...

**Comment by eantowne** [comment]
No, they are different sizes. The link provided for the one already in the appliance file, goes to the download for the full version of ASAv. the one from CML is a bandwidth and feature restricted version for use only in CML.

**Comment by grossmj** [comment]
> No, they are different sizes. The link provided for the one already in the appliance file, goes to the download for the full version of ASAv. The one from CML is a bandwidth and feature restricted version for use only in CML.

Oh I see. I haven't checked but an user would only have one of these images and I don't think we would have an issue since we use the checksum to know which image it is. If this doesn't work then I would give preference to the CML image

**Comment by eantowne** [comment]
Ok, so it generally should not be an issue to have two file names be the same in an appliance file. I will make the additions in a little bit, and you should see a new PR later, maybe tomorrow.
