### ISSUE TITLE
QEMU appliance for multiple processor architectures

### ISSUE THREAD

**Issue by ghost** [GNS3/gns3-registry#685]
Currently for QEMU appliances the processor architecture is a global setting (qemu/arch) in the appliance file. So when I want to create an appliance for both the Intel and ARM processor architecture I currently have to create two .gns3a file, one with `"arch": "x86_64"` containing the Intel images and another one with `"arch": "aarch64"` containing the ARM images.

Are there any plans to allow multiple processor architectures within a single appliance?

**Comment by grossmj** [comment]
Right, we should allow a list. I will implement this.

**Comment by grossmj** [comment]
Correct, a simple list is well... too simplistic ;) After you listed all the problems, I have the same conclusion as you: two appliance files is the best option.
