### ISSUE TITLE
check.py reports duplicate image filenames

### ISSUE THREAD

**Issue by ghost** [GNS3/gns3-registry#687]
Currently `check.py` reports an error in cisco-asav.gns3a and juniper-vrr.gns3a, that they contain duplicate image filenames. After reporting this error `check.py` stops testing further appliances.

```
$ python3 check.py
=> Check appliances
Check danos.gns3a
Check arista-ceos.gns3a
.
.
Check f5-bigip.gns3a
Check cisco-asav.gns3a
Duplicate image filename asav9-16-2.qcow2
$
```

These duplicate images were allowed by @grossmj in <https://github.com/GNS3/gns3-registry/issues/678#issuecomment-1196042244>. Maybe `check.py` should be changed so that this condition won't stop the check.

**Comment by grossmj** [comment]
Hi, have you closed this issue because it takes us too long to add your changes? ;)
