### ISSUE TITLE
New Appliance Different Versions but same image filename

### ISSUE THREAD

**Issue by josephillips85** [GNS3/gns3-registry#702]
Hi 
Im creating a new appliance but different versions use the same filename 
Example 

Appliance 1.0 = imagefile.qcow2  md5=123456
Appliance 2.0 = imagefile.qcow2 md5=7891011
GN3 send the md5 warning with the newest version but if you ignore you will see the same image on both versions.

how can be handled on this situation?

**Comment by eantowne** [comment]
You can change the name for the file. The filename really does not matter as far as I can tell, as it seems to validate by the md5 hash. So you could use something like the below:

Appliance 1.0 = imagefile-1.0.qcow2 md5=123456
Appliance 2.0 = imagefile-2.0.qcow2 md5=7891011
