### ISSUE TITLE
DNS Docker - Add Notes 

### ISSUE THREAD

**Issue by miyoung9999** [GNS3/gns3-registry#703]
Hi 

Can you add a note to adosztal/dns docker appliance please?

Would like to get added following

If you require DNS requests to be serviced from a different subnet than the one that the DNS server resides on then do the following,

1. Edit (nano or vim) /ect/init.d/dnsmasq 
2. find the line DNSMASQ_OPTS="$DNSMASQ_OPTS --local-service"
3. remove the --local-service or comment that line out and add  DNSMASQ_OPTS=""
4. restart dnsmasq - service dnsmaq restart

**Comment by grossmj** [comment]
Notes added, thanks 👍
