### ISSUE TITLE
New Windows (client) appliance

### ISSUE THREAD

**Issue by branzo** [GNS3/gns3-registry#708]
Apparently Microsoft released Windows 11 test VMs (to replace the long gone ModernIE, I guess).

https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/

Would it be possible to have it added to the templates?

**Comment by eantowne** [comment]
I will try to build this over the long weekend.

A couple of observations, totally just my opinion.

24GB .vmdk
"By using the virtual machines, you are accepting the [EULAs](https://aka.ms/windowsdevelopervirtualmachineeula) for all the installed products listed above" - That is pretty open ended.

**Comment by grossmj** [comment]
If this is of any help, I was able to install Windows 11 in a Qemu VM using the following commands on Ubuntu Jammy:

Install the TPM emulator swtpm

```
sudo add-apt-repository ppa:stefanberger/swtpm-jammy
sudo apt update
sudo apt install swtpm
```

Install OVMF:

```
sudo apt install ovmf
```

Run swtpm:

```
swtpm socket --tpm2 --tpmstate dir=/tmp/emulated_tpm --ctrl type=unixio,path=/tmp/emulated_tpm/swtpm.sock
```

Run Qemu:

```
qemu-system-x86_64 -enable-kvm -m 4096 -smp 2 -cpu host -device ac97 -audiodev alsa,id=snd0,out.buffer-length=500000,out.period-length=726 -usb -device usb-tablet -device virtio-keyboard-pci -net nic -net user -cdrom Win11_22H2_English_x64v1.iso -hda win11.img -machine q35,smm=on -global driver=cfi.pflash01,property=secure,value=on -drive if=pflash,format=raw,unit=0,file=/usr/share/ovmf/OVMF.fd,readonly=on -drive if=pflash,format=raw,unit=1,file=OVMF_VARS.fd -chardev socket,id=chrtpm,path="/tmp/emulated_tpm/swtpm.sock" -tpmdev emulator,id=tpm0,chardev=chrtpm -device tpm-tis,tpmdev=tpm0 
```

**Comment by eantowne** [comment]
This request is actually on my todo list for tonight. Just have to finish configuring this FortiGate in preparation for an ADVPN project and a dedicated Factorio Server :). I should hopefully have something tonight.

I am hoping that the VM's do not require TPM. If they do, then it will require additional instructions beyond just a simple appliance with 25GB virtual disk.

**Comment by eantowne** [comment]
Of course MS also does not provide a .qcow2, because no one would use KVM, right?

**Comment by grossmj** [comment]
I am hoping that the VM's do not require TPM.

Hopefully not. If they do then we plans to add a TPM option in GNS3 to make things easier: https://github.com/GNS3/gns3-gui/issues/3402

**Comment by eantowne** [comment]
Realistically, it would be a good thing to add for the future anyway. Additionally, with the Windows local server going away, that will make it a bit easier I would think.

**Comment by eantowne** [comment]
Looking at the .ovf file, I am going to need to create a new appliance file. The current windows.gns3a only uses 1GB RAM and 1 core. The .ovf specifies 4 cores and 4096 GB RAM.

**Comment by eantowne** [comment]
@grossmj  What is the current recommended appliance schema? I see a lot of the appliances are using v4, but there is also a v5 and v6 schema.

**Comment by grossmj** [comment]
> @grossmj What is the current recommended appliance schema? I see a lot of the appliances are using v4, but there is also a v5 and v6 schema.

I think you can use v4 for now. v5 and v6 add a few settings.

**Comment by eantowne** [comment]
Ok, thanks!

**Comment by eantowne** [comment]
@grossmj I do not think this is going to work.

- After converting the 24GB .vmdk to .qcow2, new .qcow2 size is 46GB!
- Neither the .vmdk nor the .qcow2 are able to boot. "Boot failed: could not read the boot disk"

**Comment by eantowne** [comment]
Could this be an EFI issue? I thought the current versions of ovmf include tianocore to allow for EFI booting? Or is there an option needed to be added to specify EFI?

**Comment by eantowne** [comment]
Figured out tianocore, still working through this.

**Comment by eantowne** [comment]
Got it working, final testing in progress. Should have a PR in a few minutes.

**Comment by eantowne** [comment]
PR [723](https://github.com/GNS3/gns3-registry/pull/723) submitted.

@grossmj 
@branzo

**Comment by eantowne** [comment]
@grossmj Recommend to "close as completed"
