### ISSUE TITLE
Ubuntu, CentOS and Oracle up to date cloud images are missing

### ISSUE THREAD

**Issue by elico** [GNS3/gns3-registry#718]
Currently CentOS 8 stream is the latest cloud image while in the registry the old version of CentOS is the latest.
It's the same for both Ubuntu and also there is no Oracle Enterprise Linux.

It's very simple to create a gns3a template for all of these.
If any help is needed let me know.

**Comment by eantowne** [comment]
Feel free to fork, update (or create) the appliances, and submit a PR. Keeping appliance files up-to-date for all of the appliances can be a lot of work, and the Dev team is probably more focused on GNS3 3.0, than the appliances specifically.

Please ensure that you follow the instructions in the README thoroughly. This will greatly increase the smooth merge of any PR's submitted.

**Comment by elico** [comment]
@eantowne I will try to follow on this.
There is no need to keep everything up-to-date but once in a while it's good to make sure that things are up-to-date.

**Comment by grossmj** [comment]
@elico do you have any update on this? thanks :)

**Comment by elico** [comment]
@grossmj I will try to verify in the comming week.

**Comment by elico** [comment]
@grossmj I submitted a PR at:
https://github.com/GNS3/gns3-registry/pull/717

The last time I updated GNS3 to 2.2.37 and updated the registry I didn't had Oracle Enterprise Linux so I assume it wasn't pushed?

**Comment by grossmj** [comment]
@elico sorry I missed your reply. Looks like we are missing the "Oracle Enterprise Linux" appliance file (.gns3a)

**Comment by elico** [comment]
@grossmj it's a cloud image with a cloud-init iso.
I am not sure I understood. What can I help with this matter?

**Comment by grossmj** [comment]
Sorry I may have missed somthing, I understand we have to update https://github.com/GNS3/gns3-registry/blob/master/appliances/centos-cloud.gns3a and https://github.com/GNS3/gns3-registry/blob/master/appliances/ubuntu-cloud.gns3a to use the cloud images you created in your PR https://github.com/GNS3/gns3-registry/pull/717. We also need to create a gns3a template to use the Oracle cloud image. Is this correct?

**Comment by elico** [comment]
Probably.

**Comment by elico** [comment]
@grossmj the latest releases should be at:
* https://docs.oracle.com/en-us/iaas/images/oracle-linux-8x/
* https://yum.oracle.com/templates/OracleLinux/OL8/u7/x86_64/OL8U7_x86_64-kvm-b148.qcow
* https://yum.oracle.com/oracle-linux-templates.html

**Comment by grossmj** [comment]
I have added a new Oracle Linux Cloud Guest appliance file: https://github.com/GNS3/gns3-registry/pull/764 however I could not make it work. Version 8.7 seems to boot (I could see with VNC) but then appears to be stuck, version 9.1 there is a kernel panic :(

**Comment by grossmj** [comment]
@b-ehlers thanks for clearing those last hurdles :+1: I will update the PR soon.

**Comment by grossmj** [comment]
Thanks, I have updated https://github.com/GNS3/gns3-registry/pull/764 and both version 8.7 and 9.1 work well now :+1:
