### ISSUE TITLE
cumulus-linux update required to 5.3.1

### ISSUE THREAD

**Issue by elico** [GNS3/gns3-registry#720]
NVIDIA Acquired cumulus and their latest version is 5.3.1 and the gns3a needed to be updated with the new details.
I have a copy of the VM and I will try to submit a PR with the updated details.

**Comment by grossmj** [comment]
Thanks a lot 🙏

**Comment by elico** [comment]
@grossmj I have used 5.3.1 in virtualbox and found it very unstable ie the CPU goes to 100% after an auto completion try ie: `net<tab><tab>` and stays like this for a very long time so it needs more testing then I imagined.
I will try to continue in the GNS3 community forum.
