### ISSUE TITLE
[Feature Request] Different hardware configurations as an override for a version of an appliance

### ISSUE THREAD

**Issue by eantowne** [GNS3/gns3-registry#726]
Some of the appliances have CPU/RAM/NIC requirements based on a vendors older generations of a product.

An example of this is Fortinet's FortiManager, 7.x.x versions now require 8GB RAM, and 4 cores. However versions 6.x.x and lower did not have these requirements. How do we handle this? I see a couple of different options:

1. Create new appliance file based on the new generation
2. Modify the schema to allow an override for RAM/CPU/NIC's in the specific version within "version"
3. Modify the schema so that the hardware configuration is maintained within the "version" solely

Option 1 may cause confusion among the user base as to which appliance to use and when.
Option 2 may cause more work to manage the override values.
Option 3 will cause a major set of changes to the schema's and more work for everyone.

**Comment by grossmj** [comment]
I think I would prefer option 2 or option 3. Option 3 sounds more flexible, we could have "hardware profiles" that we can link with a specific version however option 2 would be easier to implement.

**Comment by eantowne** [comment]
I like option 3 as well, however, as you stated, it would be more work. This would also allow for variations of a version. For instance I have a multi-RE and multi PFE Juniper vMX .gns3a that I use, but it will not work in the current .gns3a's for the vMX in the registry.

**Comment by grossmj** [comment]
This will be implemented in https://github.com/GNS3/gns3-registry/issues/734
