### ISSUE TITLE
Which versions of schemas are supported on which versions of GNS3?

### ISSUE THREAD

**Issue by eantowne** [GNS3/gns3-registry#727]
With 3.0 on the horizon, I was considering going through and updating appliances to newer schemas in order to support newer features provided in the latest schemas. However, I realized this may cause some serious issues. I would think that previous versions of GNS3 may not support the newest schema's if a user were to "Update from registry".

How should this be handled?

As an example, if I created an appliance that required TPM, and used schema v7 to provide that configuration item, what happens when a previous version of GNS3 tries to open that appliance template? I believe there have been issues already reported on GNS3.com for people who upgraded to 2.2.36, then had to downgrade and the "TPM" entry caused issues.

Does there need to be a property added to the schema's to specify GNS3 minimum version, then checks in the GUI/Server to deal with this?

At the very least, we may need a reference somewhere that details which GNS3 version was the starting point for each schema version.

**Comment by eantowne** [comment]
So, once an appliance is created, we should probably never upgrade the schema version in order to ensure backwards compatibility.

With a major version change such as 3.0, conceivably a new registry could be created with a new schema definition and all of the appliances could be updated. Might even be able to remove some REALLY old appliance versions as well removing any that may be broken or unmaintained, if no one wants to do the work to update them.

Sorry, I should have realized that appliance.py is checking these things. I would have been able to pull the versioning info, thanks for the reference!

**Comment by grossmj** [comment]
> So, once an appliance is created, we should probably never upgrade the schema version in order to ensure backwards compatibility.

Basically yes, backwards compatibility is always an issue ;) As mentioned by @b-ehlers above, we could at least make schema 4 the new default as I don't think anyone uses GNS3 under version 2.0...

> With a major version change such as 3.0, conceivably a new registry could be created with a new schema definition and all of the appliances could be updated. Might even be able to remove some REALLY old appliance versions as well removing any that may be broken or unmaintained, if no one wants to do the work to update them.

3.0 is the opportunity to make major changes like suggested in https://github.com/GNS3/gns3-registry/issues/726 and clean things out (more suggestions welcome!). I am also thinking about a new registry to start fresh with 3.0

@b-ehlers thanks for the schema table. I will use it to update the README.

**Comment by eantowne** [comment]
I like the idea of a new registry for 3.0, fresh start and all that. My concern would be the level of work involved. The GNS3.com Marketplace would need some changes to accompany as well.

**Comment by grossmj** [comment]
> I like the idea of a new registry for 3.0, fresh start and all that. My concern would be the level of work involved. The GNS3.com Marketplace would need some changes to accompany as well.

I think it would be worth it. Let me check the lever of work involved.

**Comment by grossmj** [comment]
Please see https://github.com/GNS3/gns3-registry/discussions/729

**Comment by eantowne** [comment]
Discussion in [#729](https://github.com/GNS3/gns3-registry/discussions/729) covers this issue, closing
