### ISSUE TITLE
Arista vEOS appliances

### ISSUE THREAD

**Issue by branzo** [GNS3/gns3-registry#728]
Howdy,

I was looking forward to start to contribute actively by updating the vEOS (and maybe cEOS) appliances files when I  realized that things have changed a bit on Arista's side:

-  md5sums for vmdks are not provided anymore in favour of sha512sums
- appliances require vEOS-lab-$version.vmdk file but from 4.22 onwards a vEOS64-lab-$version.vmdk is available.

Is it something worth discussing?

**Comment by eantowne** [comment]
"md5sums for vmdks are not provided anymore in favour of sha512sums"
You can calculate these for yourself (on Linux: `md5sum <filename>`)

"appliances require vEOS-lab-$version.vmdk file but from 4.22 onwards a vEOS64-lab-$version.vmdk is available"
You will need to add a new image section for the new image(s)

**Comment by grossmj** [comment]
@branzo Do you have more questions?

**Comment by branzo** [comment]
@grossmj not at the moment, going to close the issue.
