### ISSUE TITLE
Add Mikrotik WinBox Docker Container

### ISSUE THREAD

**Issue by alexhorner** [GNS3/gns3-registry#761]
Hi there,

I would like to publish a Docker container I have made which contains Mikrotik's WinBox router management software and is set up to either work standalone, or as a GNS3 appliance using the built in VNC support.

I have contacted Mikrotik and received permission to redistribute the WinBox binaries as part of this container, and they have also said they will make it clearer what the terms of redistribution are by adding that to the application in some kind of about window in a future version.

I am asking here in an issue before doing any kind of PR because the readme in the Docker directory within this repository suggests that it is only for officially maintained images:

```
Container maintained by the GNS3 team.
```

My container's repo is: https://github.com/alexhorner/winbox-dockerised
And it is published on Docker Hub at: https://hub.docker.com/r/alexhorner/winbox-dockerised

Thanks!

**Comment by grossmj** [comment]
Hi, your contribution is welcome. For security/validation purposes, please provide provide a Dockerfile in your PR and we will then build and push the image on our Docker hub account.

Thanks!

**Comment by alexhorner** [comment]
Would you be happy if it was a small dockerfile pointing to the docker hub image, so that I don't have to PR here just to maintain things? I see there are several other images which work this way, some.of which not from official company authors

**Comment by grossmj** [comment]
> Would you be happy if it was a small dockerfile pointing to the docker hub image, so that I don't have to PR here just to maintain things? I see there are several other images which work this way, some.of which not from official company authors.

Yes, this should be fine 👍 thanks.
