### ISSUE TITLE
F5 BIG-IP LTM load balancer

### ISSUE THREAD

**Issue by adosztal** [GNS3/gns3-registry#77]
I can create the appliance file for this LB. I'd need:
- to know which category I should use
- an empty 100G image (according to [this document](https://support.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/bigip-ve-kvm-setup-11-3-0/1.html#unique_1479977860)), the same way you provided for Fortinet

**Comment by noplay** [comment]
Good question.  @grossmj what should be the category for F5? And the symbol?

For the disk:
```json
        {
            "filename": "empty100G.qcow2",
            "version": "1.0",
            "md5sum": "1e6409a4523ada212dea2ebc50e50a65",
            "filesize": 198656,
            "download_url": "https://sourceforge.net/projects/gns-3/files/Empty%20Qemu%20disk/",
            "direct_download_url": "http://downloads.sourceforge.net/project/gns-3/Empty Qemu disk/empty100G.qcow2"
        }
```

**Comment by noplay** [comment]
Thanks a lot for your help

**Comment by adosztal** [comment]
No problem. :) Actually, I already learned a lot about KVM/Qemu, so thanks for the opportunity.

[This](https://conceptdraw.com/a1777c3/p48/preview/640/pict--ace-cisco-products-additional---vector-stencils-library.png--diagram-flowchart-example.png) is the Cisco icon for load balancers but there are [several others](https://www.google.hu/search?q=load+balancer+icon&safe=off&client=ubuntu&hs=VNH&channel=fs&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwjF4-v9r7bKAhVG8ywKHUoNDsYQsAQIHQ&biw=1568&bih=916) too.

**Comment by adosztal** [comment]
One more thing about the console: both vnc and telnet works but which one should we use?
- vnc: you can see the grub menu and the whole boot process but disconnects after grub and the terminal has to be opened again
- telnet: works fine but the boot process is quite long (even on SSD) and there's no output until the login prompt appears; the users might think the system doesn't boot.

**Comment by noplay** [comment]
Personaly I prefer telnet because no keyboard layout issue. You can add a note in the usage field saying the boot will be long.

**Comment by adosztal** [comment]
Will do, thanks.

**Comment by adosztal** [comment]
So, what about the category and the symbol for load balancers? @noplay @grossmj

**Comment by noplay** [comment]
@grossmj ?

For the category a router or a firewall?

**Comment by grossmj** [comment]
Good question... it's a load balancer but router is what come the closest I would say ;)

**Comment by adosztal** [comment]
Okay. I'll get the 12.0 image from my colleague tomorrow morning, then I can finalize the file.

**Comment by noplay** [comment]
I made a proposal for an icon #79
