### ISSUE TITLE
Status of docker images endhost, haproxy, network_automation_pycharm and openvswitch28

### ISSUE THREAD

**Issue by ghost** [GNS3/gns3-registry#791]
@AJNOURI As far as I know you created the docker images endhost, haproxy, network_automation_pycharm and openvswitch28.

These are not used by any appliance. Are they still used? Or can they be deleted?

**Comment by grossmj** [comment]
> @grossmj I propose the following: Delete both images at DockerHub and wait one or two month if anyone complains. If you decide to keep these images, then create appliances and enable them in the docker build system. Otherwise they can be deleted.

I am unsure too. I can only see the last activity for an image on DockerHub, endhost was pulled 1 hour ago and haproxy 8 days ago.

**Comment by grossmj** [comment]
Indeed they are still used, please can you create a PR? Thanks 🙏
