### ISSUE TITLE
Huawei

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-registry#81]
Don't know what to do, but it's a common query from users.

**Comment by noplay** [comment]
It seem something called eNSP exist

From jeremy:
```
Virtual devices in eNSP runs in VirtualBox so in theory it should be possible to have an integration however without any help we have to plan for it soon.
```

**Comment by noplay** [comment]
http://support.huawei.com/enterprise/toolNewInfoAction!toToolDetail?contentId=TL1000000015&productLineId=0602_ROOT

**Comment by noplay** [comment]
And doc from matt:
https://gns3.com/news/article/connecting-huawei-ensp-to-gns3

**Comment by ehlers** [comment]
I don't see, how a Huawei appliance could be created.

Huawei has it's own simulator, called eNSP, which can be installed within Windows and which has it's own cloud interface, which can be connected to the GNS3 cloud interface. That's what Matt describes in his doc. Huawei delivers an installer for windows. Of cause someone can build a Windows 7 VM with that eNSP installed and that could be added here in the registry. But I'm sure, that will violate the copyrights of Huawei and Microsoft.

Another way is try to extract the HUAWEI router image out of the eNSP and integrate that in GNS3. Technically it may be possible. For the AR devices there is a AR_Base.vdi within eNSP. It's about 140MB large, based on TinyCore Linux and simulates the AR device family from Huawei. But it uses only UDP tunnels to communicate to other devices and you have to upload a (undocumented) resource file via FTP into this VM to configure those UDP tunnels. So it might be tricky to integrate that, but it's not impossible. But again the HUAWEI copyright will prohibit (at least in my understanding) to put an image, that is based upon AR_base.vdi on some server, so it can be used here.

**Comment by noplay** [comment]
How the vdi is run? It's a qemu? 

Extracting the image. It's not impossible. Users are doing that for VIRL before CISCO released the images.

We can't provide them. But  providing a documentation explaining how to extract them. Once they extracted it we can import it and configure it.

And one day Huawei will see that users want this and it's good for their business

**Comment by ehlers** [comment]
vdi is the native disk format for VirtualBox, qemu-img should be able to convert it into qcow2. Also VBoxManage can convert vdi into vmdk, what qemu can work with. So the vdi format is easy to deal with.

When someone manages to modify the Huawei software and publishes the procedure, anyone can use it to build it's own image and use it with GNS3. It's similar like the olive images made from the juniper junos. It's interesting, helps people using it with GNS3, but that's not an **appliance**.

That derived image can't be published, because of legal problems. So I'm pessimistic only about the possibility to create an **appliance**, but not about the possibility to integrate Huawei.

**Comment by ehlers** [comment]
BTW: I was trying to use the AR_Base.vdi outside eNSP. It sends some random data out of COM2 and seems to want a key as a reply. If I send some random data, the VM terminates with an error message.

Giving up.

**Comment by grossmj** [comment]
Yep, Huawei stuff is a bit complicated to reverse-engineer... I didn't figure it out when I tried a year ago.

**Comment by adosztal** [comment]
I looked/asked around:
- eNSP is definitely a no-go
- the virtual router's download page [is empty](http://support.huawei.com/enterprise/en/router/ar1000v-pid-21768212/software)

I think this issue can be closed. I'll check once in a while if something will be available.
