### ISSUE TITLE
Maintainer for vyos appliance wanted

### ISSUE THREAD

**Issue by ghost** [GNS3/gns3-registry#816]
As I have no longer access to the vyos LTS versions, I can no longer update the vyos appliance. It already shows, as the latest version 1.3.3 is missing.

For keeping the vyos appliance up-to-date someone with access to the LTS versions is needed.

**Comment by grossmj** [comment]
> Now you have to open https://vyos.net/get/ and fill out a form to get the links to the old releases.

I did it and they only give access to the legacy 1.2.9-S1 version :(

> Furthermore I have no access to the current release 1.3.x, therefore the releases in the appliance are getting old.

Let me try if we can get a subscription as a non-profit organization before we decide removing VyOS.

**Comment by elico** [comment]
It's very simple to build the 1.3.3 ISO using docker.
I cannot maintain the appliance but can supply a simple creation script.

**Comment by grossmj** [comment]
I have contacted the VyOS team and they offered us a partnership, part of it is they would maintain the VyOS appliance on the GNS3 marketplace. Hopefully this should be finalized soon.

**Comment by elico** [comment]
@grossmj the VyOS project has a very good documentation on how to build the ISO:
https://docs.vyos.io/en/latest/contributing/build-vyos.html

I can publish my basic and simple scripts that builds VyOS regularilly.
Currently the VyOS LTS version is 1.4 which is an upgrade from the 1.3.3.

**Comment by elico** [comment]
@elico I started using the rolling version since it's stable enough for general usage.
If there are specific bugs you can report them and they will be resolved later on.
There is only a need to download the ISO and upload it without a signature.

**Comment by grossmj** [comment]
The VyOS appliance was recently updated by the VyOS Inc.: https://github.com/GNS3/gns3-registry/pull/911
