### ISSUE TITLE
Big Switch appliances

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-registry#83]
http://www.bigswitch.com/community-edition

See if we can integrate these Big Monitoring Fabric and Big Cloud Fabric Community Editions.

**Comment by noplay** [comment]
I have asked for access

**Comment by noplay** [comment]
https://github.com/GNS3/gns3-registry/blob/67b9363f251cd3f348cf8fa35911e9a09e4a8533/appliances/bigswitch-bigcloud-fabric.gns3a
