### ISSUE TITLE
Purge Old Images from the appliances I Update?

### ISSUE THREAD

**Issue by Da-Geek** [GNS3/gns3-registry#834]
So, what is the deal with removing Old/Obsolete images from the .gns3a files?

For some of the appliances I have been updating, we have a list of older images
that are no longer available, officially retired, or deprecated in some way.

When I am adding a New/Updated version of an Image, what is the position
on those older ones, can/should I just remove then?
Or what about adding a [OUTDATED] or [DEPRECATED] string to the old images?
delete the Download URL?

What do we think, before I start deleting a Bunch of things the next time I update
an appliance?

**Comment by grossmj** [comment]
Yes please just delete officially retired or deprecated images.

Thanks 👍
