### ISSUE TITLE
Schema 6 update in PR #732 missing in schema 7 and 8

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-registry#849]
In PR #732 the schema 6 (schemas/appliance_v6.json) got some small [updates](https://github.com/GNS3/gns3-registry/pull/732/files#diff-c0293c6d58ec6dbef7bae8d897d9a98bcbb51e75aa63585cb71cd728fd3badee), but these changes were not added to schema 7 (schemas/appliance_v7.json). While the addition of qemu console_type "spice+agent" made it into schema 8 (schemas/appliance_v8.json), the console_type "none" was not added into 8.

Is that done intentionally? Or are the updates missing in v7 and v8?

**Comment by grossmj** [comment]
Thanks for catching that 👍
