### ISSUE TITLE
ONIE

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-registry#85]
Could be usefull for simulating withebox switch.
http://onie.opencompute.org/

https://github.com/opencomputeproject/onie/blob/master/machine/kvm_x86_64/INSTALL

**Comment by adosztal** [comment]
I'm afraid this is too complex. The only purpose of such appliance would be to test how ONIE gets a NOS to the VM, not an average networking lab.
I suggest dropping it and closing this issue.
