### ISSUE TITLE
Latest FortiGate Images for GNS3

### ISSUE THREAD

**Issue by CookieCr2nk** [GNS3/gns3-registry#858]
Hello,

Is it possible to add the latest Fortigate Firmware to the File https://github.com/GNS3/gns3-server/blob/master/gns3server/appliances/fortigate.gns3a, so it can be used in GNS3.

Latest Fortigate VM Versions downloadable from Fortinet (https://support.fortinet.com/Download/VMImages.aspx):

    6.4.15
    7.0.14
    7.2.7
    7.4.3

**Comment by eantowne** [comment]
I was planning on doing that this weekend. In the meantime, you can use the option to either "create a new version" on the import or "allow custom files" to bypass the hash check. I will try and get the new versions added this weekend, as well as for FAZ/FMG.

**Comment by eantowne** [comment]
[PR #859](https://github.com/GNS3/gns3-registry/pull/859#issue-2138797113) submitted.

Includes most current version of FGT (as requested) along with updates for FMG/FAZ.
