### ISSUE TITLE
Tinycore appliance upgrade or an alternative thin linux appliance

### ISSUE THREAD

**Issue by elico** [GNS3/gns3-registry#864]
Tinycore linux is now on version 15 while the appliance is on version 11.
I might be able to try and help to work on the 15 version but no promises.

I am looking for the right tiny linux distro to be an alternative for VPC node.
The options I was thinking about were:
* Alpine linux
* TinyCore Linux
* OpenWRT
* other

**Comment by josephmhiggins** [comment]
You have to build requirements for the supported features **you** want for the docker.

I would base my search on supported features:
shell name(dont'care), dhcp client, all dhcpv6 client methods, non-gui, telnet, trace

Almost all gns3 users just use vpcs for dhcp and pings.
I do not use vpcs.

**Comment by grossmj** [comment]
> I might be able to try and help to work on the 15 version but no promises.

Do you mean you would like to update the Qemu appliance found on https://github.com/GNS3/gns3-registry/blob/master/packer/tinycore-linux/tinycore-linux.json ?

**Comment by elico** [comment]
Not relevant due to the existence of alpine linux cloudinit compatible image.
