### ISSUE TITLE
Adding Open VSwitch appliance bash completion

### ISSUE THREAD

**Issue by elico** [GNS3/gns3-registry#878]
I have tried to use the open vswitch appliance as an alternative to others like aruba and similar switches.
Eventually I found myself with a working appliance that do not have cli completion.
It's very simple to update the openvswitch docker container to have both bash and the relevant bash completion for OVS commands.

Just to write it down:
* <https://www.cyberciti.biz/faq/alpine-linux-enable-bash-command-autocomplete/>
* <https://docs.openvswitch.org/en/latest/intro/install/bash-completion/#ovs-vsctl-bashcomp>

no time limit to reach the goal but it would be nice to have the relevant packages and files installed.

**Comment by grossmj** [comment]
I have opened a PR to add bash completion: https://github.com/GNS3/gns3-registry/pull/882
