### ISSUE TITLE
FortiGate 7.4.4 wrong build number

### ISSUE THREAD

**Issue by bikkio** [GNS3/gns3-registry#906]
Hi all

in GNS3 2.2.49 i noticed that the FortiGate template for version 7.4.4 report the same build number of 7.4.3.

Wrong:
FGT_VM64_KVM-v7.4.4.F-**build2573**-FORTINET.out.kvm.qcow2
FGT_VM64_KVM-v7.4.3.F-build2573-FORTINET.out.kvm.qcow2

It should be FGT_VM64_KVM-v7.4.4.F-build2662-FORTINET.out.kvm.qcow2

Regards

Marco

**Comment by grossmj** [comment]
@bikkio thank for spotting this. Do you know if the size is the same as FGT_VM64_KVM-v7.4.3.F-build2573-FORTINET.out.kvm.qcow2? (100728832 bytes)

**Comment by bikkio** [comment]
@grossmj the sizes is different

FGT_VM64_KVM-v7.4.3.F-build2573-FORTINET.out.kvm.qcow2 (100728832 bytes)
FGT_VM64_KVM-v7.4.4.F-build2662-FORTINET.out.kvm.qcow2 (102170624 bytes)

**Comment by grossmj** [comment]
@bikkio thanks, I have created a PR to fix this issue: https://github.com/GNS3/gns3-registry/pull/907

Please review and I will merge if everything is good. Thanks.
