### ISSUE TITLE
Ubuntu container: "gns3/ubuntu:latest not found"

### ISSUE THREAD

**Issue by HarimbolaSantatra** [GNS3/gns3-registry#913]
When running: `docker pull gns3/ubuntu`

There's the error:
```
Using default tag: latest
Error response from daemon: manifest for gns3/ubuntu:latest not found: manifest unknown: manifest unknown
```

Pulling works fine on different container (tested with chromium and webterm).

**Comment by HarimbolaSantatra** [comment]
Apparently, it works when I use either focal or noble: `docker pull gns3/ubuntu:noble`.

**Comment by grossmj** [comment]
Correct, we don't have the `latest` tag: https://hub.docker.com/r/gns3/ubuntu/tags
