### ISSUE TITLE
TrueNAS appliance

### ISSUE THREAD

**Issue by scls19fr** [GNS3/gns3-registry#915]
Hello,

We have [FreeNAS appliance](https://github.com/GNS3/gns3-registry/blob/59dea90647c6d5a56813adcb86fb8d2f8f92a591/appliances/freenas.gns3a) but maybe TrueNAS appliance for GNS3 could added to this repository.

Kind regards

**Comment by grossmj** [comment]
Hi,

I see you have created `truenas.gns3a`. Are you going to create a pull request or do you prefer us to use this file to create the appliance?

Thanks :+1:

**Comment by scls19fr** [comment]
Hi @grossmj ,

I have not much experience about creating GNS3 appliance.
Creating is not the much important thing I think. But **testing** is.
Could you have a look at this ?
You can take "my" file (which is in fact inspired by freenas appliance)

Kind regards

**Comment by scls19fr** [comment]
I added images values (filename, md5sum, filesize...) for SCALE (both release and beta) which is Debian base (while CORE is FreeBSD based)
