### ISSUE TITLE
ReactOS version is incorrect

### ISSUE THREAD

**Issue by scls19fr** [GNS3/gns3-registry#920]
Hello,

ReactOS version in GNS3 appliances is incorrect

Compare

https://github.com/GNS3/gns3-registry/blob/4045b06622d74868f646598080b969e204c934d4/appliances/reactos.gns3a#L27

with

https://github.com/GNS3/gns3-registry/blob/4045b06622d74868f646598080b969e204c934d4/appliances/reactos.gns3a#L32

Release 15 vs 21

Pinging @saviodsouza

Kind regards

**Comment by saviodsouza** [comment]
Fixing this today 

Sorry for for the incorrect version update

**Comment by saviodsouza** [comment]
Fixing this today 

Sorry for for the incorrect version update

**Comment by saviodsouza** [comment]
https://github.com/GNS3/gns3-registry/pull/921

**Comment by grossmj** [comment]
@saviodsouza thanks for fixing it 👍
