### ISSUE TITLE
Bug? file missing on website?

### ISSUE THREAD

**Issue by chaeynz** [GNS3/gns3-registry#924]
I made this commit and the PR got merged
https://github.com/GNS3/gns3-registry/commit/60a025c0472fb78894f3473e58789b6ec61ed27e

However, I can't see the version 7.14.2 on the website?
https://www.gns3.com/marketplace/appliances/mikrotik-cloud-hosted-router

**Comment by grossmj** [comment]
Looks like you had forgotten to add the 7.14.2 version in `versions` array.

```
        {
            "name": "7.14.2",
            "images": {
                "hda_disk_image": "chr-7.14.2.img"
            }
        },
```

I have updated the appliance with the latest versions. The website should be automatically updated soon.

**Comment by chaeynz** [comment]
Lol That's so embarassing. I could swear I had seen the version on the website already. Thank you @grossmj ! :D
