### ISSUE TITLE
traceroute in webterm appliance raises a segfault

### ISSUE THREAD

**Issue by s-celles** [GNS3/gns3-registry#926]
Hello,

I'm trying this lab
https://cyberlab.pacific.edu/courses/comp177/labs/lab-4-dynamic-routing
and noticed the following problem

    / # traceroute 10.40.0.1
    traceroute to 10.40.0.1 (10.40.0.1), 30 hops max, 46 byte packets
     1Segmentation fault (core dumped)

Any idea what is wrong with this appliance?

Kind regards

PS : using `trace` with a VPCS can be a workaround.

**Comment by grossmj** [comment]
Sorry, I am not sure why.

I tested it and couldn't find any issue. Maybe it comes from your environment?

![Image](https://github.com/user-attachments/assets/81898d8b-0f14-4c59-aac8-2cd033c2f8bc)

Do you have a simple topology that you can reproduce the problem?

**Comment by s-celles** [comment]
The topology was quite similar than yours (ie very simple). but my GNS3 install was done using this settings https://benheater.com/proxmox-gns3-remote-server/
I currently don't use it and my VM have been deleted so I will reopen if it occurs again in a new install
