### ISSUE TITLE
f5 ve 

### ISSUE THREAD

**Issue by jejanobs** [GNS3/gns3-registry#93]
the f5 gnsa that is used supports only big-ip 12.0.0 and big-ip 11.6.0
version but F5 offers an free version of the bip-ip and that is bip-ip 11.3.0.

can you please change this in the gnsa appliance to support also version 11.3.0

**Comment by noplay** [comment]
Hi,

We need the filesize and the md5 sum of the file to add this.

Thanks

**Comment by jejanobs** [comment]
Hi,

the file size of the big-ip BIGIP-11.3.0.39.0-scsi.ova is 701.860 kB and 
BIGIP-11.3.0.39.0-scsi.ova.md5 size is 1kB the sum is: 6d1714a2baf1264bfd9bfa1284e876de
thanks

this is an free version

**Comment by noplay** [comment]
What is the exact size in bytes for BIGIP-11.3.0.39.0-scsi.ova? Thanks for the help

**Comment by jejanobs** [comment]
the size is 685 MB

**Comment by noplay** [comment]
Sorry but I need the exact size you can get it with  ls -l if you are under linux.

**Comment by jejanobs** [comment]
oke than this is the good size : (718.704.640 bytes)
 sorry

**Comment by noplay** [comment]
Thanks!

**Comment by noplay** [comment]
Tested and it will not work. It's an ova and we need qcow2. We can support
OVA but since F5 has provide qcow2 for other release we prefer to use them
because qcow2 is the native format for qemu.

Where did you get the OVA? Perhaps we can found the corresponding qcow2.

Thanks for the help

**Comment by jejanobs** [comment]
I got the OVA from the F5 website from the download section. there you 
can download a free 90 days trail version for VE.


https://downloads.f5.com/esd/product.jsp?sw=BIG-IP&pro=big-ip_v11.x&ver=11.3.0




Julien Duponchelle schreef op 2016-02-22 09:39:
> Tested and it will not work. It's an ova and we need qcow2. We can
> support
> OVA but since F5 has provide qcow2 for other release we prefer to use
> them
> because qcow2 is the native format for qemu.
> 
> Where did you get the OVA? Perhaps we can found the corresponding
> qcow2.
> 
> Thanks for the help
> 
> On Fri, Feb 19, 2016 at 6:01 PM Julien Duponchelle <julien@gns3.net>
> wrote:
> 
>> Thanks!
>> 
>> On Fri, Feb 19, 2016 at 4:17 PM jejanobs <notifications@github.com>
> wrote:
>> 
>>> oke than this is the good size : (718.704.640 bytes)
>>> sorry
>>> 
>>> —
>>> Reply to this email directly or view it on GitHub
>>> 
> <https://github.com/GNS3/gns3-registry/issues/93#issuecomment-186255633>.
>>> 
>> 
> --
> Reply to this email directly or view it on GitHub [1].
> 
> 	*
> 
> Links:
> ------
> [1] 
> https://github.com/GNS3/gns3-registry/issues/93#issuecomment-187073632

-- 
Met Vriendelijke Groeten,

Lloyd Bouterse
ASCIST B.V.

Cypresbaan 27
2908 LT Capelle a/d IJssel
010 2840227

www.ascist.net

**Comment by noplay** [comment]
Ok they have a qcow2 in the same directory.

I can also download the version 11.6 from the same site. The 11.6 version
is not free for you?

**Comment by jejanobs** [comment]
yess i can download the 11.6 version but i don't have the keys to 
actived  license.

i ordered the low cost lab version but i am waiting still (that is 
version F5 BIG-IP Virtual Edition Lab License (LTM, GTM, DNS, AFM, ASM, 
APM Lite, AAM, CGN, SSL Forward Proxy, Advanced Protocols, Crypto 
Offload, 10 Mbps, v11.4.1 - v15.x)

v
Julien Duponchelle eschreef op 2016-02-22 17:32:
> Ok they have a qcow2 in the same directory.
> 
> I can also download the version 11.6 from the same site. The 11.6
> version
> is not free for you?
> 
> On Mon, Feb 22, 2016 at 11:04 AM jejanobs <notifications@github.com>
> wrote:
> 
>> I got the OVA from the F5 website from the download section. there
> you
>> can download a free 90 days trail version for VE.
>> 
>> 
>> 
>> 
> https://downloads.f5.com/esd/product.jsp?sw=BIG-IP&pro=big-ip_v11.x&ver=11.3.0
>> 
>> 
>> 
>> 
>> Julien Duponchelle schreef op 2016-02-22 09:39:
>> > Tested and it will not work. It's an ova and we need qcow2. We can
>> > support
>> > OVA but since F5 has provide qcow2 for other release we prefer to
> use
>> > them
>> > because qcow2 is the native format for qemu.
>> >
>> > Where did you get the OVA? Perhaps we can found the corresponding
>> > qcow2.
>> >
>> > Thanks for the help
>> >
>> > On Fri, Feb 19, 2016 at 6:01 PM Julien Duponchelle
> <julien@gns3.net>
>> > wrote:
>> >
>> >> Thanks!
>> >>
>> >> On Fri, Feb 19, 2016 at 4:17 PM jejanobs
> <notifications@github.com>
>> > wrote:
>> >>
>> >>> oke than this is the good size : (718.704.640 bytes)
>> >>> sorry
>> >>>
>> >>> —
>> >>> Reply to this email directly or view it on GitHub
>> >>>
>> >
> <https://github.com/GNS3/gns3-registry/issues/93#issuecomment-186255633
>> >.
>> >>>
>> >>
>> > --
>> > Reply to this email directly or view it on GitHub [1].
>> >
>> > *
>> >
>> > Links:
>> > ------
>> > [1]
>> >
> https://github.com/GNS3/gns3-registry/issues/93#issuecomment-187073632
>> 
>> --
>> Met Vriendelijke Groeten,
>> 
>> Lloyd Bouterse
>> ASCIST B.V.
>> 
>> Cypresbaan 27
>> 2908 LT Capelle a/d IJssel
>> 010 2840227
>> 
>> www.ascist.net
>> 
>> —
>> Reply to this email directly or view it on GitHub
>> 
> <https://github.com/GNS3/gns3-registry/issues/93#issuecomment-187105133>.
>> 
> --
> Reply to this email directly or view it on GitHub [1].
> 
> 	*
> 
> Links:
> ------
> [1] 
> https://github.com/GNS3/gns3-registry/issues/93#issuecomment-187255206

-- 
Met Vriendelijke Groeten,

Lloyd Bouterse
ASCIST B.V.

Cypresbaan 27
2908 LT Capelle a/d IJssel
010 2840227

www.ascist.net

**Comment by noplay** [comment]
Ok I added the 11.3 qcow2

**Comment by noplay** [comment]
Thanks!

**Comment by jejanobs** [comment]
thank you so much for your time and help.

 
i am gonne try if it works in gns

**Comment by jejanobs** [comment]
hi,
first i want to thank you for your patience and help.
now i went to the website of gns3 to download the appliance but i see that the did not update their appliance yet. On the github website i see the change you made but i can not download the appliance..what am i doing wrong? help me
