### ISSUE TITLE
f5 ve appliance update

### ISSUE THREAD

**Issue by jejanobs** [GNS3/gns3-registry#99]
hi,
first i want to thank you for your patience and help.
now i went to the website of gns3 to download the f5 appliance but i see that the did not update their appliance yet. On the github website i see the change you made but i can not download the appliance..what am i doing wrong? or can you update the f5 aplliance on the gns3 website?

**Comment by noplay** [comment]
It's just a redirection :( You don't get the last? Perhaps a browser cache

**Comment by jejanobs** [comment]
I got it started with the appliance but when i login to start the big-ip i get this massage:
Cannot connect to mcpd
Cannot connect to mcpd. Your preferences and aliases will not be available until it comes back up.
The connection to mcpd has been lost, try again.

localhost emerg logger: Re-starting chmand
localhost emerg logger: Re-starting chmand
localhost emerg logger: Re-starting chmand

**Comment by jejanobs** [comment]
i did found the qcow2 version on the f5 site and it has another size than the one i send you. could that be the problem?

**Comment by adosztal** [comment]
Could you try adding the following to the additional options field? "-cpu host"
